#!/usr/bin/env bash

# Source the script 'common-functions.sh'.
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/common-functions.sh"

_main() {
    local input_files=""
    local output_dir=""

    # Execute initial checks.
    _check_dependencies "command=git | command=xclip"
    _display_wait_box "2"
    input_files=$(_get_files "par_type=directory; par_max_files=1; par_get_pwd=true")
    output_dir=$input_files

    # Execute the function '_main_task' for each file in parallel.
    _run_task_parallel "$(_get_urls_from_clipboard)" "$output_dir"
    _display_result_box "$output_dir"
}

_main_task() {
    local input_file=$1
    local output_dir=$2
    local std_output=""

    cd "$output_dir" || return 1

    # Run the main process.
    std_output=$(git clone -q -- "$input_file" 2>&1)
    _check_output "$?" "$std_output" "$input_file" "" || return 1
}

_get_urls_from_clipboard() {
    local urls=""

    urls+=$(xclip -quiet -selection primary -o)
    urls+=$'\n'
    urls+=$(xclip -quiet -selection secondary -o)
    urls+=$'\n'
    urls+=$(xclip -quiet -selection clipboard -o)
    urls+=$'\n'
    urls=$(grep --only-matching --perl-regexp "((git|ssh|http(s)?)|(git@[\w\.]+))(.*)(\.git)" <<<"$urls")
    urls=$(sort -u <<<"$urls")

    if [[ -z "$urls" ]]; then
        _display_error_box "There are no valid URLs in the clipboard!"
        _exit_script
    fi

    _convert_text_to_filenames "$urls"
}

_main "$@"
