#!/usr/bin/env bash
# install_keyboard_shortcut=<Control><Alt>V

# Source the script 'common-functions.sh'.
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/common-functions.sh"

_main() {
    local output_dir=""

    # Execute initial checks.
    case "${XDG_SESSION_TYPE,,}" in
    "x11") _check_dependencies "command=xclip" ;;
    "wayland") _check_dependencies "command=wl-paste; package=wl-clipboard" ;;
    *)
        _display_error_box "Unknown session type!"
        _exit_script
        ;;
    esac

    _display_wait_box "2"
    output_dir=$(_get_working_directory)

    # Execute the function '_main_task' for each file in parallel.
    _run_task_parallel "$(_get_urls_from_clipboard)" "$output_dir"
    _display_result_box "$output_dir"
}

_main_task() {
    local input_file=$1
    local output_dir=$2
    local std_output=""

    cd "$output_dir" || return 1

    if ! [[ -e "$input_file" ]]; then
        return 1
    fi

    # Run the main process.
    output_file=$(_get_output_filename "$input_file" "$output_dir" "par_extension_opt=preserve")
    std_output=$(cp -Ral -- "$input_file" "$output_file" 2>&1)
    _check_output "$?" "$std_output" "$input_file" "$output_file" || return 1
}

_get_urls_from_clipboard() {
    local urls=""

    if [[ "${XDG_SESSION_TYPE,,}" == "x11" ]]; then
        urls=$(xclip -quiet -selection clipboard -o)
    elif [[ "${XDG_SESSION_TYPE,,}" == "wayland" ]]; then
        urls=$(wl-paste)
    fi
    urls=$(grep --only-matching --perl-regexp "^(file://|('\")?/)(.*)" <<<"$urls")
    urls=$(sed "s|^['\"]||g; s|['\"]$||g" <<<"$urls")
    urls=$(sort -u <<<"$urls")

    if [[ -z "$urls" ]]; then
        _display_error_box "There are no valid paths in the clipboard!"
        _exit_script
    fi

    urls=$(_convert_text_to_filenames "$urls")
    urls=$(_text_uri_decode "$urls")

    printf "%s" "$urls"
}

_main "$@"
