#!/usr/bin/env bash

# Source the file 'scripts/common-functions'
# shellcheck disable=SC1090
source "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")" | sed -z 's|\(scripts\).*|\1/common-functions|')"

# Initial checks
_check_dependency inkscape
INPUT_FILES=$(_check_files "$*" "svg" "1" "" "") || exit 1

ERROR_COUNT=0
for FILE in $INPUT_FILES; do
    # Run the main process
    OUTPUT_FILE="$(_remove_extension "$FILE").pdf"
    STD_OUTPUT="$(inkscape -D -z --file="$FILE" --export-pdf="$OUTPUT_FILE" 2>&1)"

    # Check if output file is not a zero byte
    if [ "$(stat --printf="%s" "$OUTPUT_FILE")" == "0" ]; then
        ERROR_COUNT=$((ERROR_COUNT + 1))

        # Log the error in a file
        _log_error "$FILE" "$STD_OUTPUT"
    fi
done

_display_result "$ERROR_COUNT" ""
