#!/usr/bin/env bash

# Source the script 'common-functions.sh'.
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/common-functions.sh"

_main() {
    local input_files=""

    # Execute initial checks.
    _check_dependencies ""
    input_files=$(_get_files "par_type=all, par_get_pwd=true")

    # shellcheck disable=SC2086
    # Run the main process.
    if _command_exists "code"; then
        code -- $input_files &
    elif _command_exists "geany"; then
        geany -- $input_files &
    elif _command_exists "gnome-text-editor"; then
        gnome-text-editor -- $input_files &
    elif _command_exists "gedit"; then
        gedit -- $input_files &
    elif _command_exists "xed"; then
        xed -- $input_files &
    else
        _check_dependencies "gedit"
        gedit -- $input_files &
    fi
}

_main "$@"
