#!/usr/bin/env bash

# Source the script 'common-functions.sh'.
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/common-functions.sh"

_main() {
    local input_files=""

    # Execute initial checks.
    _check_dependencies ""
    input_files=$(_get_files "par_type=directory; par_max_files=1; par_get_pwd=true")

    # Run the main process.
    if [[ "${XDG_CURRENT_DESKTOP,,}" == *"kde"* ]]; then
        _check_dependencies "command=filelight"
        filelight -- "$input_files" &
    else
        _check_dependencies "command=baobab"
        baobab -- "$input_files" &
    fi
}

_main "$@"
