#!/usr/bin/env bash
# install_keyboard_shortcut=F4

# Source the script 'common-functions.sh'.
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/common-functions.sh"

_main() {
    local input_files=""

    # Execute initial checks.
    _check_dependencies ""
    input_files=$(_get_files "par_type=directory; par_max_items=20")
    _unset_global_variables_file_manager

    _open_app "$input_files"
}

_open_app() {
    local input_files=$1
    local available_app=""
    local apps=(
        "ptyxis"
        "gnome-terminal"
        "kgx"
        "konsole"
        "xfce4-terminal"
        "mate-terminal"
        "xterm"
        "kitty"
        "alacritty"
        "terminator"
        "qterminal"
        "deepin-terminal"
        "terminology"
        "uxterm"
        "termit"
    )
    available_app=$(_get_available_app "apps")

    # Iterate over each input file (directory).
    local input_file=""
    for input_file in $input_files; do
        # Special handling for some apps.
        if [[ "$available_app" == "ptyxis" ]]; then
            $available_app --new-window --working-directory "$input_file" &
        else
            _directory_push "$input_file" || continue
            $available_app &
            _directory_pop || continue
        fi
    done
}

_main "$@"
