#!/usr/bin/env bash

# Source the script 'common-functions.sh'.
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/common-functions.sh"

_main() {
    local input_files=""

    # Execute initial checks.
    _check_dependencies ""
    input_files=$(_get_files "par_type=directory; par_max_files=1; par_get_pwd=true")

    # shellcheck disable=SC2086
    # Run the main process.
    if _command_exists "gnome-terminal"; then
        gnome-terminal --working-directory="$input_files" &
    elif _command_exists "mate-terminal"; then
        mate-terminal --working-directory="$input_files" &
    elif _command_exists "xfce4-terminal"; then
        xfce4-terminal --default-working-directory="$input_files" &
    elif _command_exists "konsole"; then
        konsole --workdir "$input_files" &
    else
        _check_dependencies "command=gnome-terminal"
        gnome-terminal --working-directory="$input_files" &
    fi
}

_main "$@"
