#!/usr/bin/env bash

# Source the script 'common-functions.sh'
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/common-functions.sh"

_main() {
    local input_files=""

    # Initial checks
    _check_dependencies "code"
    input_files=$(_get_files "$*" "type=all; get_pwd_if_no_selection=true")

    # Run the main process
    # shellcheck disable=SC2086
    code -- $input_files &
}

_main "$@"
