#!/usr/bin/env bash

# Import the script 'common-functions.sh'
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
source "${SCRIPT_DIR/%scripts\/*/scripts}/common-functions.sh"

# Initial checks
_check_dependencies "code"
INPUT_FILES=$(_get_files "$*" "type=all; get_pwd_if_no_selection=true")

# Run the main process
# shellcheck disable=SC2086
code $INPUT_FILES &
