#!/usr/bin/env bash

# Source the script 'common-functions.sh'
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/common-functions.sh"

_main() {
    local input_files=""
    local std_output=""

    # Initial checks
    _check_dependencies "pdfinfo(poppler-utils)"
    _display_wait_box
    input_files=$(_get_files "$*" "type=file; recursive=true; mime=pdf")

    _run_task_parallel "$input_files" ""

    std_output=$(cat "$TEMP_DIR_TASK/"* 2>/dev/null) # Compile the result in a single text
    std_output=$(grep -v "^$" <<<"$std_output")      # Remove empty lines
    # shellcheck disable=SC2001
    std_output=$(sed "s|$PWD/|./|g" <<<"$std_output")  # Remove dir $PWD of the filename
    std_output=$(sort --version-sort <<<"$std_output") # Sort the result

    _display_text_box "$std_output"
}

_main_task() {
    local input_file=$1
    local output_dir=$2
    local temp_file=""

    # Save the result only for 'encrypted' PDFs
    if pdfinfo -- "$input_file" | grep "Encrypted:" | grep --quiet "yes ("; then
        # Work on a temporary file
        temp_file=$(mktemp --tmpdir="$TEMP_DIR_TASK")
        echo "\"$input_file\"" >"$temp_file"
    fi
}

_main "$@"
