#!/usr/bin/env bash

# Source the script '.common-functions.sh'.
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/.common-functions.sh"

_main() {
    local input_files=""
    local output_dir=""

    # Execute initial checks.
    _command_exists "magick" || _check_dependencies "convert"
    _display_wait_box
    input_files=$(_get_files "par_type=file; par_select_mime=image/")

    TEMP_DATA_TASK=$(_display_file_selection_box \
        "$(_i18n 'Choose an image to use as the watermark')" \
        "$(_i18n 'Image files') | *.bmp *.gif *.png *.jpg *.jpeg *.tif")

    # Check output directory only after displaying dialog boxes to the user.
    output_dir=$(_get_output_dir "par_use_same_dir=true")

    # Execute the function '_main_task' for each file in parallel.
    _run_task_parallel "$input_files" "$output_dir"
    _display_result_box "$output_dir"
}

_main_task() {
    local input_file=$1
    local output_dir=$2
    local output_file=""
    local std_output=""
    local gravity="south"

    output_file=$(_get_output_filename "$input_file" "$output_dir" "par_extension_opt=preserve; par_suffix='(watermark)'")

    # Run the main process.
    std_output=$(_cmd_magick_convert "$input_file" "$TEMP_DATA_TASK" -gravity "$gravity" -composite "$output_file" 2>&1)
    _check_output "$?" "$std_output" "$input_file" "$output_file" || return 1
}

_main "$@"
