#!/usr/bin/env bash
# shellcheck disable=SC2001

# Source the script 'common-functions.sh'.
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/common-functions.sh"

_main() {
    local input_files=""
    local output_dir=""

    # Execute initial checks.
    _check_dependencies ""
    _display_wait_box "2"
    input_files=$(_get_files "par_type=all")

    # Execute the function '_main_task' for each file in parallel.
    _run_task_parallel "$input_files" "$output_dir"
    _display_result_box ""
}

_main_task() {
    local input_file=$1
    local output_dir=$2
    local output_file=""
    local std_output=""
    local dir=""
    local filename=""
    local filename_extension=""

    dir=$(dirname -- "$input_file")
    filename=$(basename -- "$input_file")
    filename_extension=$(_get_filename_extension "$input_file")

    # Transform to title case.
    output_file=$(sed "s|’|'|g" <<<"$filename")
    output_file=$(sed "s|\(\w\)\(\w*\)|\U\1\L\2|g" <<<"$output_file")

    # Define the list of words to lowercase
    local words=""
    words="a|an|and|as|at|but|by|for|if|in|nor|of|off|on|or|per|so|the|to|up|via|yet"
    output_file=$(sed -E "s/([ ])($words)\b/\1\L\2/gI" <<<"$output_file")
    words="a|e|o|da|das|de|do|dos|na|no|para|pra|um|uma"
    output_file=$(sed -E "s/([ ])($words)\b/\1\L\2/gI" <<<"$output_file")
    output_file=$(sed -E "s|(- \w)|\U\1|g" <<<"$output_file")

    # Fix some common words.
    output_file=$(sed "s|\('\w\)|\L\1|gI" <<<"$output_file")
    output_file=$(sed "s| \(d'\w\)| \U\1|gI" <<<"$output_file")
    output_file=$(sed "s| \(o'\w\)| \U\1|gI" <<<"$output_file")
    output_file=$(sed "s| o'| O'|gI" <<<"$output_file")
    output_file=$(sed "s| '\(\w\)| '\U\1|gI" <<<"$output_file")
    output_file=$(sed "s| no\.| No.|gI" <<<"$output_file")
    output_file=$(sed "s|feat\.|feat\.|gI" <<<"$output_file")
    output_file=$(sed -E "s/ (IX|IV|V?I{0,3})([,\. ])/ \U\1\2/gI" <<<"$output_file")

    output_file=$(_strip_filename_extension "$output_file")

    # Run the main process.
    std_output=$(_move_file "skip" "$input_file" "$dir/$output_file${filename_extension,,}" 2>&1)
    _check_output "$?" "$std_output" "$input_file" "" || return 1
}

_main "$@"
