#!/usr/bin/env bash

# Source the file 'scripts/common-functions'
# shellcheck disable=SC1090
source "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")" | sed 's|\(scripts\).*|\1/common-functions|')"

# Initial checks
_check_dependencies make
INPUT_FILES=$(_get_files "$*" "text/x-makefile" "1" "" "") || exit 1
OUTPUT_DIR="$PWD"

for FILE in $INPUT_FILES; do
    # Run the main process
    STD_OUTPUT="$(make -f "$FILE" 2>&1)"
    EXIT_CODE=$?

    _check_successful_finish "$FILE" "$STD_OUTPUT" "$OUTPUT_DIR" "$EXIT_CODE" "$OUTPUT_FILE"
done

_display_result "$OUTPUT_DIR"
