#!/usr/bin/env bash

# Source the file 'scripts/common-functions'
source "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")" | sed -z 's|\(scripts\).*|\1/common-functions|')"

# Initial checks
_check_dependency make
_check_number_files $# 1

ERROR_COUNT=0
FILES_COUNT=0
MIME_TYPES="text/x-makefile"

for arg; do
    # Filter files with a specific mime type
    if [ "$(_check_mime_type "$arg" "$MIME_TYPES")" == "0" ]; then
        FILES_COUNT=$(($FILES_COUNT + 1))

        # Run the main process
        STD_OUTPUT="$(make -f "$arg" clean 2>&1)"
        EXIT_CODE=$?

        # Check the return
        if [ "$EXIT_CODE" -ne 0 ]; then
            ERROR_COUNT=$(($ERROR_COUNT + 1))

            # Log the error in a file
            _log_error "$arg" "$STD_OUTPUT"
        fi
    fi
done

_display_final_result "$FILES_COUNT" "$ERROR_COUNT" "$MIME_TYPES" ""
