#!/usr/bin/env bash

# Source the file 'scripts/common-functions'
# shellcheck disable=SC1090
source "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")" | sed 's|\(scripts\).*|\1/common-functions|')"

# Initial checks
_check_dependency cmake
_check_files "$*" "text/x-c" "1" "1" "" || exit 1
OUTPUT_DIR=$(_get_output_dir)

{
    pushd "$PWD" || ERROR_COUNT=$((ERROR_COUNT + 1))
    cd "$OUTPUT_DIR" || ERROR_COUNT=$((ERROR_COUNT + 1))
} &>/dev/null

if [ "$ERROR_COUNT" -eq 0 ]; then
    # Run the first step
    STD_OUTPUT="$(cmake .. 2>&1)"
    EXIT_CODE=$?

    # Check the return
    if [ "$EXIT_CODE" -ne 0 ]; then
        ERROR_COUNT=$((ERROR_COUNT + 1))

        # Log the error in a file
        _log_error "cmake .." "$STD_OUTPUT"
    fi

    # Run the second step
    STD_OUTPUT="$(cmake --build . 2>&1)"
    EXIT_CODE=$?

    # Check the return
    if [ "$EXIT_CODE" -ne 0 ]; then
        ERROR_COUNT=$((ERROR_COUNT + 1))

        # Log the error in a file
        _log_error "cmake --build ." "$STD_OUTPUT"
    fi

    {
        popd || ERROR_COUNT=$((ERROR_COUNT + 1))
    } &>/dev/null
fi

_display_result "$ERROR_COUNT" "$OUTPUT_DIR"
