#!/usr/bin/env bash

# shellcheck disable=SC2001

# Source the file 'scripts/common-functions'
# shellcheck disable=SC1090
source "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")" | sed 's|\(scripts\).*|\1/common-functions|')"

# Initial checks
_check_dependencies zenity || exit 1
INPUT_FILES=$(_get_files "$*" "" "1" "" "r") || exit 1

# Run the main process
# shellcheck disable=SC2086
STD_OUTPUT=$(file $INPUT_FILES)
STD_OUTPUT=$(echo "$STD_OUTPUT" | sed "s|\([^:]*\):[ \t]*\(.*\)|\2: '\1'|")
STD_OUTPUT=$(echo "$STD_OUTPUT" | sort -V)

WIDTH_TEXT=$(echo "$STD_OUTPUT" | wc -L)
WIDTH_WINDOW=$((WIDTH_TEXT * 10))
echo "$STD_OUTPUT" | zenity --text-info --no-wrap --font="Liberation Mono" --height=300 --width="$WIDTH_WINDOW" --title "File informations ('file' command)"
