#!/usr/bin/env bash

# shellcheck disable=SC2001

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
# shellcheck source=/dev/null
source "${SCRIPT_DIR%/*}/common-functions"

# Initial checks
_check_dependencies rdfind || exit 1
INPUT_FILES=$(_get_files "$*" "" "1" "" "d") || exit 1

# Create a temp file in a temporary directory
# (this directory is removed after finish by a 'trap' command)
TEMP_FILE=$(mktemp --tmpdir="$TEMP_DIR")

# Run the main process
# shellcheck disable=SC2086
rdfind -dryrun true -outputname "$TEMP_FILE" $INPUT_FILES
STD_OUTPUT=$(cat "$TEMP_FILE")
STD_OUTPUT=$(echo "$STD_OUTPUT" | grep -v "^#")
STD_OUTPUT=$(echo "$STD_OUTPUT" | cut -d ' ' -f 1,8-)
STD_OUTPUT=$(echo "$STD_OUTPUT" | sed "s|\([^ ]*\)[ \t]*\(.*\)|\1 \"\2\"|")
STD_OUTPUT=$(echo "$STD_OUTPUT" | sed "s|DUPTYPE_FIRST_OCCURRENCE|\nDUPTYPE_FIRST_OCCURRENCE|")
STD_OUTPUT=$(echo "$STD_OUTPUT" | cut -d ' ' -f 2-)

_display_info_box "$STD_OUTPUT" "Duplicate files"
