#!/usr/bin/env bash

# Source the file 'scripts/common-functions'
# shellcheck disable=SC1090
source "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")" | sed 's|\(scripts\).*|\1/common-functions|')"

# Initial checks
_check_dependencies fdupes || exit 1
INPUT_FILES=$(_get_files "$*" "" "1" "" "d") || exit 1

# Run the main process
# shellcheck disable=SC2086
STD_OUTPUT=$(fdupes -r $INPUT_FILES)
STD_OUTPUT=$(echo "$STD_OUTPUT" | sed -r "s|(.+)|\"\1\"|")

_display_info_box "$STD_OUTPUT" "Duplicate files"
