#!/usr/bin/env bash

# Source the file 'scripts/common-functions'
# shellcheck disable=SC1090
source "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")" | sed 's|\(scripts\).*|\1/common-functions|')"

# Initial checks
_check_dependencies zenity
INPUT_FILES=$(_get_files "$*" "" "1" "" "R")

# Run the main process
# shellcheck disable=SC2086
STD_OUTPUT=$(stat -c "%a %U %G %F: '%n'" $INPUT_FILES)
STD_OUTPUT="$(echo "$STD_OUTPUT" | sort)"
WIDTH_TEXT=$(echo "$STD_OUTPUT" | wc -L)
WIDTH_WINDOW=$((WIDTH_TEXT * 10))
echo "$STD_OUTPUT" | zenity --text-info --no-wrap --font="Liberation Mono" --height=300 --width="$WIDTH_WINDOW" --title "File informations (permissions and owner)"
