#!/usr/bin/env bash

# Source the file 'scripts/common-functions'
# shellcheck disable=SC1090
source "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")" | sed 's|\(scripts\).*|\1/common-functions|')"

# Initial checks
_check_dependencies zenity || exit 1
INPUT_FILES=$(_get_files "$*" "" "1" "" "r") || exit 1

# Run the main process
# shellcheck disable=SC2086
STD_OUTPUT=$(sha512sum $INPUT_FILES)

_display_info_box "$STD_OUTPUT" "SHA512 sum"
