#!/usr/bin/env bash

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
# shellcheck source=/dev/null
source "${SCRIPT_DIR%/*}/_common_functions"

# Initial checks
_check_dependencies zenity || exit 1
INPUT_FILES=$(_get_files "$*" "F" "1" "" "") || exit 1

# Run the main process
# shellcheck disable=SC2086
STD_OUTPUT=$(sha256sum $INPUT_FILES)

_display_info_box "$STD_OUTPUT" "SHA256 sum"
