#!/usr/bin/env bash

# Source the script '.common-functions.sh'.
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/.common-functions.sh"

_main() {
    local input_files=""

    # Execute initial checks.
    _check_dependencies ""
    _display_wait_box
    input_files=$(_get_files "par_type=file; par_max_items=1; par_select_mime=text/plain")

    # Execute the function '_verify_checksum' for each file in parallel.
    export -f _verify_checksum
    _run_function_parallel "_verify_checksum '{}'" "$(<"$input_files")" "\n"

    local std_output=""
    std_output=$(_storage_text_read_all)
    std_output=$(_text_sort "$std_output")

    # Translate some strings from the '$std_output'.
    # shellcheck disable=SC2001
    std_output=$(sed "s|__MSG_Ok__|$(_i18n 'Ok')|g" <<<"$std_output")
    # shellcheck disable=SC2001
    std_output=$(sed "s|__MSG_Mismatch__|$(_i18n 'Checksum mismatch.')|g" <<<"$std_output")
    # shellcheck disable=SC2001
    std_output=$(sed "s|__MSG_NotFound__|$(_i18n 'File does not exist.')|g" <<<"$std_output")

    _display_list_box "$std_output" "par_item_name=$(_i18n 'files'); par_columns='--column:$(_i18n 'Status'),--column:$(_i18n 'File')'; par_action=open_location; par_check_type=checkbox"
}

_verify_checksum() {
    local line=$1
    local saved_checksum=""
    local saved_file=""
    local current_output=""
    local current_checksum=""
    local status=""

    saved_checksum=$(printf "%s" "$line" | cut -d " " -f1)
    saved_file=$(printf "%s" "$line" | cut -d " " -f3-)

    # Replace % to %% with the 'printf' command.
    saved_file=${saved_file//%/%%}

    # Some checksums start with '\', for filenames with '\n' or '\'.
    # shellcheck disable=SC2059
    saved_file_decoded=$(printf "$saved_file")

    # If the file does not exist, report and skip the check.
    if [[ ! -e "$saved_file_decoded" ]]; then
        status="🔴 __MSG_NotFound__"
        _storage_text_write_ln "$status$FIELD_SEPARATOR$saved_file"
        return 1
    fi

    # Run the main process.
    current_output=$(md5sum -- "$saved_file_decoded" 2>/dev/null)
    current_checksum=$(printf "%s" "$current_output" | cut -d " " -f1)

    # Compare the checksum.
    if [[ "$saved_checksum" != "$current_checksum" ]]; then
        status="🔴 __MSG_Mismatch__"
        _storage_text_write_ln "$status$FIELD_SEPARATOR$saved_file"
        return 1
    fi

    status="🟢 __MSG_Ok__"
    _storage_text_write_ln "$status$FIELD_SEPARATOR$saved_file"
}

_main "$@"
