#!/usr/bin/env bash

# Source the file 'scripts/common-functions'
# shellcheck disable=SC1090
source "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")" | sed 's|\(scripts\).*|\1/common-functions|')"

# Initial checks
_check_dependencies pandoc || exit 1
INPUT_FILES=$(_get_files "$*" "" "1" "" "") || exit 1
OUTPUT_DIR=$(_get_output_dir) || exit 1

_run_task() {
    local FILE="$1"
    local OUTPUT_DIR="$2"
    local STD_OUTPUT=""
    local EXIT_CODE=0

    OUTPUT_FILE="$OUTPUT_DIR/$(_get_filename_without_extension "$FILE").md"
    STD_OUTPUT="$(pandoc "$FILE" -t markdown -s -o "$OUTPUT_FILE" 2>&1)"
    EXIT_CODE=$?
    _log_result_error "$FILE" "$STD_OUTPUT" "$OUTPUT_DIR" "$EXIT_CODE" "$OUTPUT_FILE"
}

_parallel_run "$INPUT_FILES"
_display_result "$OUTPUT_DIR"
