#!/usr/bin/env bash

# Source the script '.common-functions.sh'.
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/.common-functions.sh"

_main() {
    local input_files=""
    local output_dir=""

    # Execute initial checks.
    _check_dependencies "exiftool"
    _display_wait_box "2"
    input_files=$(_get_files "par_type=file; par_select_mime='image/|video/'")

    # Execute the function '_main_task' for each file in parallel.
    _run_task_parallel "$input_files" "$output_dir"
    _display_result_box ""
}

_main_task() {
    local input_file=$1
    local output_dir=$2
    local output_file=""
    local dir=""
    local filename=""

    dir=$(dirname -- "$input_file")
    filename=$(basename -- "$input_file")

    # Ignore files that already follow the expected timestamp prefix.
    if [[ "$filename" == [0-9]???-??-??_??-??-??_* ]]; then
        return
    fi

    # Extract the creation date from metadata (first match only).
    local date=""
    date=$(exiftool -s -s -s -duplicates -CreateDate -DateTimeOriginal \
        "$input_file" 2>/dev/null | sed -n "1p" | sed "s|:|-|g; s| |_|g")

    # Abort if no creation date is available.
    if [[ -z "$date" ]]; then
        return
    fi

    # Run the main process.
    _move_file "skip" "$input_file" "$dir/${date}_$filename" || return 1
}

_main "$@"
