#!/usr/bin/env bash

# Source the script '.common-functions.sh'.
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/.common-functions.sh"

_main() {
    local input_files=""
    local output_dir=""

    # Execute initial checks.
    _check_dependencies "tar gpg"
    input_files=$(_get_files "par_type=file; par_select_mime='application/octet-stream|application/pgp|application/pgp-encrypted|text/plain'")
    output_dir=$(_get_output_dir "par_use_same_dir=true")

    # Execute the function '_main_task' for each file in parallel.
    _run_task_parallel "$input_files" "$output_dir"
    _display_result_box "$output_dir"
}

_main_task() {
    local input_file=$1
    local output_dir=$2
    local output_file=""
    local std_output=""

    output_file=$(_get_output_filename "$input_file" "$output_dir" "par_extension_opt=strip")

    # Run the main process.
    std_output=$(gpg --batch --yes --decrypt --output "$output_file" -- "$input_file" 2>&1)
    _check_output "$?" "$std_output" "$input_file" "$output_file" || return 1

    # If the output file is a tar archive, extract it.
    local file_mime=""
    file_mime=$(_get_file_mime "$output_file")
    if [[ "$file_mime" == "application/x-tar" ]]; then
        # Create a temporary local directory for extraction.
        local basename=""
        local temp_dir_local=""
        basename=$(basename -- "$input_file")             # Remove the path.
        basename=$(_strip_filename_extension "$basename") # Remove the extension.
        temp_dir_local=$(_make_temp_dir_local "$output_dir" ".$basename")

        _directory_push "$temp_dir_local" || return 1
        std_output=$(tar --extract --file="$output_file" 2>&1)
        _check_output "$?" "$std_output" "$input_file" "" || return 1
        _directory_pop || return 1
        rm -f -- "$output_file"
        mv -- "$temp_dir_local" "$output_file"
    fi
}

_main "$@"
