#!/usr/bin/env bash

# Source the script '.common-functions.sh'.
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/.common-functions.sh"

_main() {
    local input_files=""
    local output_dir=""

    # Execute initial checks.
    _check_dependencies "gpg"
    _display_wait_box
    input_files=$(_get_files "par_type=all")

    _get_keys_id

    # Check output directory only after displaying dialog boxes to the user.
    output_dir=$(_get_output_dir "par_use_same_dir=true")

    export -f _run_gpg

    # Execute the function '_main_task' for each file in parallel.
    _run_task_parallel "$input_files" "$output_dir"
    _display_result_box "$output_dir"
}

_main_task() {
    local input_file=$1
    local output_dir=$2
    local output_file=""

    # Determine if the input is a directory or a file.
    if [[ -d "$input_file" ]]; then
        # Check if the directory is empty.
        if _is_directory_empty "$input_file"; then
            local msg=""
            msg="$(_i18n 'The directory is empty.')"
            _log_error "$msg" "$input_file" "" "$output_file"
            return 1
        fi

        # Generate the output filename for directories.
        output_file=$(_get_output_filename "$input_file" "$output_dir" "par_extension_opt=append; par_extension=tar.asc")

        # Create a temporary local directory for archiving.
        local temp_dir_local=""
        temp_dir_local=$(_make_temp_dir_local "$output_dir" "")

        # Archive the contents of the directory into a temporary tar file.
        local temp_archive="$temp_dir_local/archive.tar"
        _directory_push "$input_file" || return 1
        std_output=$(find . -mindepth 1 -maxdepth 1 -printf "%f\0" 2>/dev/null |
            sort --zero-terminated --version-sort |
            xargs --no-run-if-empty --null tar -cf "$temp_archive" --)
        _directory_pop || return 1

        # Encrypt the archived file using GPG.
        _run_gpg "$temp_archive" "$output_file"

        # Remove the temporary directory (local directory).
        rm -rf -- "$temp_dir_local"
    else
        # Generate the output filename for regular files.
        output_file=$(_get_output_filename "$input_file" "$output_dir" "par_extension_opt=append; par_extension=asc")

        # Encrypt the input file directly using GPG.
        _run_gpg "$input_file" "$output_file"
    fi
}

_run_gpg() {
    local input_file=$1
    local output_file=$2
    local std_output=""

    IFS=$FIELD_SEPARATOR

    local recipients=()
    local user=""
    for user in $TEMP_DATA_TASK; do
        recipients+=("--recipient=$user")
    done

    std_output=$(gpg \
        --batch \
        --yes \
        --encrypt \
        "${recipients[@]}" \
        --armor \
        --output "$output_file" \
        -- "$input_file" 2>&1)

    _check_output "$?" "$std_output" "$input_file" "$output_file" || return 1
}

_import_key() {
    local input_file=""
    local std_output=""
    local key_id=""

    input_file=$(_display_file_selection_box \
        "$(_i18n 'Key files') | *.asc *.gpg *.pgp" \
        "$(_i18n 'Choose a key file to import.')")

    if [[ -z "$input_file" ]]; then
        _exit_script
    fi

    # Get the ID from the key.
    key_id=$(gpg --with-colons --import-options show-only --import "$input_file" |
        grep -m1 "^fpr" | cut -d ":" -f 10 2>/dev/null)

    # Import the key.
    std_output=$(gpg --batch --yes --import "$input_file" 2>&1)
    _check_output "$?" "$std_output" "$input_file" "" || return 1

    # Set the trust level to 'ultimate'.
    std_output=$(printf "%s\n" "$key_id:6:" | gpg --batch --yes --import-ownertrust 2>&1)
    _check_output "$?" "$std_output" "$input_file" "" || return 1
}

_get_keys_id() {
    local msg=""

    local keys=""
    keys=$(_get_public_keys)
    if [[ -z "$keys" ]]; then
        msg+="$(_i18n 'No public keys were found.')"
        msg+="\n\n"
        msg+="$(_i18n 'Would you like to import a key now?')"
        if ! _display_question_box "$msg"; then
            _exit_script
        fi
        _import_key
        keys=$(_get_public_keys)
        if [[ -z "$keys" ]]; then
            msg="$(_i18n 'Failed to import the key!')"
            _display_error_box "$msg"
            _exit_script
        fi
    fi

    keys=$(tr ":" "$FIELD_SEPARATOR" <<<"$keys")
    TEMP_DATA_TASK=$(_display_select_box "$keys" \
        "--column:$(_i18n 'Name'),--column:$(_i18n 'E-mail'),--column:$(_i18n 'Created'),--column:$(_i18n 'Expires'),--column:$(_i18n 'Key ID')" \
        "checkbox" "first_if_one" \
        "$(_i18n 'Select one or more users:')")

    if [[ -z "$TEMP_DATA_TASK" ]]; then
        msg="$(_i18n 'You must select at least one user!')"
        _display_error_box "$msg"
        _exit_script
    fi
}

_get_public_keys() {
    gpg --list-public-keys --with-colons --keyid-format LONG |
        awk -F: '
            # When the main key is found.
            $1=="pub" {
                keyid=$5
                created_ts=$6
                expire_ts=$7

                # Format creation date.
                cmd="date -d @" created_ts " +\"%Y-%m-%d\""
                cmd | getline created
                close(cmd)

                # Format expiration date (may be empty).
                if (expire_ts != "") {
                    cmd2="date -d @" expire_ts " +\"%Y-%m-%d\""
                    cmd2 | getline expire
                    close(cmd2)
                } else {
                    expire=" "
                }
            }

            # Extract name and email.
            $1=="uid" {
                match($10, /(.*) <(.*)>/, arr)
                name=arr[1]
                email=arr[2]
                print name ":" email ":" created ":" expire ":" keyid
            }'
}

_main "$@"
