#!/usr/bin/env bash

# Source the script '.common-functions.sh'.
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/.common-functions.sh"

_main() {
    local input_files=""

    # Execute initial checks.
    _check_dependencies "gpg"
    _display_wait_box
    input_files=$(_get_files "par_type=file")

    # Execute the function '_main_task'.
    _main_task "$input_files"
    _display_result_box ""
}

_main_task() {
    local input_files=$1
    local imported_count=0

    local input_file=""
    for input_file in $input_files; do
        _import_key "$input_file" || continue
        imported_count=$((imported_count + 1))
    done

    if ((imported_count == 0)); then
        input_file=$(_display_file_selection_box \
            "$(_i18n 'Key files') | *.asc *.gpg *.pgp" \
            "$(_i18n 'Choose a key file to import.')")
        if [[ -z "$input_file" ]]; then
            _exit_script
        fi
        _import_key "$input_file" && imported_count=$((imported_count + 1))
    fi

    # If keys were imported, clean up the temporary error logs.
    if ((imported_count > 0)); then
        rm -f -- "$TEMP_DIR_LOGS/"* 2>/dev/null
    fi
}

_import_key() {
    local input_file=$1
    local std_output=""
    local key_id=""

    # Get the ID from the key.
    key_id=$(gpg --with-colons --import-options show-only --import "$input_file" |
        grep -m1 "^fpr" | cut -d ":" -f 10 2>/dev/null)

    # Import the key.
    std_output=$(gpg --batch --yes --import "$input_file" 2>&1)
    _check_output "$?" "$std_output" "$input_file" "" || return 1

    # Set the trust level to 'ultimate'.
    std_output=$(printf "%s\n" "$key_id:6:" | gpg --batch --yes --import-ownertrust 2>&1)
    _check_output "$?" "$std_output" "$input_file" "" || return 1
}

_main "$@"
