#!/usr/bin/env bash

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
# shellcheck source=/dev/null
source "${SCRIPT_DIR%/*}/common-functions"

# Initial checks
_check_dependencies pdfinfo zenity || exit 1
INPUT_FILES=$(_get_files "$*" "pdf" "1" "" "r") || exit 1

_main_task() {
    local FILE=$1
    # shellcheck disable=SC2034
    local OUTPUT_DIR=$2
    local TEMP_FILE

    # Save the result only for 'not linearized (not optimized)' PDFs
    if pdfinfo "$FILE" | grep "Optimized:" | grep -q "no"; then
        # Create a temp file in a temporary directory
        # (this directory is removed after finish by a 'trap' command)
        TEMP_FILE=$(mktemp --tmpdir="$TEMP_DIR")
        echo "\"$FILE\"" >"$TEMP_FILE"
    fi
}

_run_parallel_tasks "$INPUT_FILES"
STD_OUTPUT=$(cat "$TEMP_DIR"/*)

STD_OUTPUT=$(echo "$STD_OUTPUT" | grep -v "^$")
STD_OUTPUT=$(echo "$STD_OUTPUT" | sort -V)

_display_info_box "$STD_OUTPUT" "Find files: not linearized (not optimized)"
