#!/usr/bin/env bash

# Source the file 'scripts/common-functions'
# shellcheck disable=SC1090
source "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")" | sed -z 's|\(scripts\).*|\1/common-functions|')"

# Initial checks
_check_dependency pdfunite
INPUT_FILES=$(_check_files "$*" "pdf" "2" "" "") || exit 1
OUTPUT_FILE="output.pdf"
ERROR_COUNT=0

# Run the main process
# shellcheck disable=SC2086
STD_OUTPUT="$(pdfunite $INPUT_FILES $OUTPUT_FILE 2>&1)"
EXIT_CODE=$?

# Check the return
if [ "$EXIT_CODE" -ne 0 ]; then
    ERROR_COUNT=$((ERROR_COUNT + 1))

    # Log the error in a file
    _log_error "$PDF_PARAMETER" "$STD_OUTPUT"
fi

_display_result "$ERROR_COUNT" ""
