#!/usr/bin/env bash

# Source the file 'scripts/common-functions'
# shellcheck disable=SC1090
source "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")" | sed 's|\(scripts\).*|\1/common-functions|')"

# Initial checks
_check_dependencies pdfunite
INPUT_FILES=$(_get_files "$*" "pdf" "2" "" "") || exit 1
OUTPUT_DIR=$(_get_output_dir)

# Run the main process
OUTPUT_FILE="$OUTPUT_DIR/merged.pdf"
# shellcheck disable=SC2086
STD_OUTPUT="$(pdfunite $INPUT_FILES "$OUTPUT_FILE" 2>&1)"
EXIT_CODE=$?

# Check the return and log the error
if [ "$EXIT_CODE" -ne 0 ]; then
    _log_error "$PDF_PARAMETER" "$STD_OUTPUT"
fi

_display_result "$OUTPUT_DIR"
