#!/usr/bin/env bash

# Source the file 'scripts/common-functions'
# shellcheck disable=SC1090
source "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")" | sed -z 's|\(scripts\).*|\1/common-functions|')"

# Initial checks
_check_dependency gs
INPUT_FILES=$(_check_files "$*" "pdf" "1" "" "") || exit 1
OUTPUT_DIR=$(_get_output_dir)

ERROR_COUNT=0
for FILE in $INPUT_FILES; do
    # Run the main process
    STD_OUTPUT="$(gs -q -dNOPAUSE -dBATCH -dSAFER -sDEVICE=pdfwrite -dPDFSETTINGS=/printer -sOutputFile="$OUTPUT_DIR/$FILE" "$FILE" 2>&1)"

    # Check the return
    if [[ "$STD_OUTPUT" == *"Error"* ]]; then
        ERROR_COUNT=$((ERROR_COUNT + 1))

        # Log the error in a file
        _log_error "$FILE" "$STD_OUTPUT" "$OUTPUT_DIR"
    fi
done

_display_result "$ERROR_COUNT" "$OUTPUT_DIR"
