#!/usr/bin/env bash

# Source the file 'scripts/common-functions'
# shellcheck disable=SC1090
source "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")" | sed 's|\(scripts\).*|\1/common-functions|')"

# Initial checks
_check_dependencies gs
INPUT_FILES=$(_get_files "$*" "pdf" "1" "" "") || exit 1
OUTPUT_DIR=$(_get_output_dir)

for FILE in $INPUT_FILES; do
    # Run the main process
    OUTPUT_FILE="$OUTPUT_DIR/$FILE"
    STD_OUTPUT="$(gs -q -dNOPAUSE -dBATCH -dSAFER -sDEVICE=pdfwrite -dPDFSETTINGS=/printer -sOutputFile="$OUTPUT_FILE" "$FILE" 2>&1)"

    # Check the return and log the error
    if [[ "$STD_OUTPUT" == *"Error"* ]]; then
        _log_error "$FILE" "$STD_OUTPUT" "$OUTPUT_DIR"
    fi
done

_display_result "$OUTPUT_DIR"
