#!/usr/bin/env bash

# Source the script '.common-functions.sh'.
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/.common-functions.sh"

_main() {
    local input_files=""
    local output_dir=""

    # Execute initial checks.
    _check_dependencies "iconv"
    _display_wait_box
    input_files=$(_get_files "par_type=file; par_skip_extension='bak|pdf|svg'")
    output_dir=$(_get_output_dir "par_use_same_dir=true")

    # Execute the function '_main_task' for each file in parallel.
    _run_task_parallel "$input_files" "$output_dir"
    _display_result_box "$output_dir"
}

_main_task() {
    local input_file=$1
    local output_dir=$2
    local output_file=""
    local encoding="utf-8//TRANSLIT"

    # NOTE: Sometimes 'file' command returns 'us-ascii' for 'utf-8' files.
    local input_encoding=""
    input_encoding=$(_get_file_encoding "$input_file")
    if [[ -z "$input_encoding" ]] || [[ "$input_encoding" == "binary" ]]; then
        return
    fi
    [[ "$input_encoding" == "us-ascii" ]] && input_encoding="utf-8"

    output_file=$(_get_output_filename "$input_file" "$output_dir" "par_extension_opt=preserve; par_suffix='(UTF-8)'")

    # Run the main process.
    iconv -f "$input_encoding" "$input_file" -t "$encoding" > "$output_file"
    _check_output "$?" "" "$input_file" "$output_file" || return 1
}

_main "$@"
