#!/usr/bin/env bash

# Source the script '.common-functions.sh'.
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/.common-functions.sh"

_main() {
    local input_files=""
    local output_dir=""

    # Execute initial checks.
    _check_dependencies "iconv perl"
    _display_wait_box
    input_files=$(_get_files "par_type=file; par_recursive=true; par_skip_extension='bak|pdf|svg'")

    # Execute the function '_main_task' for each file in parallel.
    _run_task_parallel "$input_files" "$output_dir"
    _display_result_box ""
}

_main_task() {
    local input_file=$1
    local output_dir=$2
    local output_file=""
    local temp_file1=""
    local temp_file2=""
    local encoding="utf-8//TRANSLIT"

    # Work on a temporary file.
    temp_file1=$(_make_temp_file)
    temp_file2=$(_make_temp_file)

    # NOTE: Sometimes 'file' command returns 'us-ascii' for 'utf-8' files.
    local input_encoding=""
    input_encoding=$(_get_file_encoding "$input_file")
    if [[ -z "$input_encoding" ]] || [[ "$input_encoding" == "binary" ]]; then
        return
    fi
    [[ "$input_encoding" == "us-ascii" ]] && input_encoding="utf-8"

    # Step 1: 'convert encoding to utf-8'.
    iconv -f "$input_encoding" "$input_file" -t "$encoding" >"$temp_file1"
    _check_output "$?" "iconv" "$input_file" "$temp_file1" || return 1

    # Step 2: 'convert line breaks to Unix'.
    perl -pe "s/\r\n|\n|\r/\n/g" "$temp_file1" >"$temp_file2" 2>/dev/null
    _check_output "$?" "perl" "$input_file" "$temp_file2" || return 1

    # Step 3: 'remove trailing spaces'.
    sed -i "s|[ \t]*\(\r*\)$|\1|" "$temp_file2"

    # Step 4: 'remove the empty line in EOF'.
    printf "\n" >>"$temp_file2"
    sed -i ':Loop;N;$!bLoop;s|\n*$||g' "$temp_file2"

    # Move the temporary file to the output.
    output_file=$input_file
    _move_file "safe_overwrite" "$temp_file2" "$output_file"

    # Remove the temporary files on each iteration (if not removed before).
    rm -f -- "$temp_file1"
    rm -f -- "$temp_file2"
}

_main "$@"
