#!/usr/bin/env bash

# Source the file 'scripts/common-functions'
# shellcheck disable=SC1090
source "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")" | sed 's|\(scripts\).*|\1/common-functions|')"

# Initial checks
_check_dependency tr
INPUT_FILES=$(_check_files "$*" "" "1" "" "d") || exit 1
OUTPUT_DIR="$PWD"

ERROR_COUNT=0
NUM_SEQUENCE=1
for FILE in $INPUT_FILES; do
    NEW_FILENAME=$(printf "%03d" $NUM_SEQUENCE)
    # shellcheck disable=SC2001
    FILENAME_EXTENSION=$(echo "$FILE" | sed "s|[^.]*\.|.|" | grep "\.")

    if [ -f "$NEW_FILENAME" ]; then
        ERROR_COUNT=$((ERROR_COUNT + 1))
        _log_error "$FILE" "It was not possible to rename the file." "$OUTPUT_DIR"
        continue
    fi

    # Run the main process
    mv "$FILE" "$NEW_FILENAME$FILENAME_EXTENSION"

    NUM_SEQUENCE=$((NUM_SEQUENCE + 1))
done

_display_result "$ERROR_COUNT" ""
