#!/usr/bin/env bash

# Import the script 'common-functions.sh'
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(echo "$SCRIPT_DIR" | grep --only-matching "^.*scripts[^/]*")
source "$ROOT_DIR/common-functions.sh"

# Initial checks
_check_dependencies "pdfinfo(poppler-utils)"
_display_wait_box
input_files=$(_get_files "$*" "type=file_recursive; mime=pdf")

_main_task() {
    local input_file=$1
    local output_dir=$2
    local temp_file=""

    # Save the result only for 'not linearized (not optimized)' PDFs
    if pdfinfo "$input_file" | grep "Optimized:" | grep --quiet "no"; then
        # Work on a temporary file
        temp_file=$(mktemp --tmpdir="$TEMP_DIR_TASK")
        echo "\"$input_file\"" >"$temp_file"
    fi
}

_run_main_task_parallel "$input_files" ""

std_output=$(cat "$TEMP_DIR_TASK"/* 2>/dev/null)
std_output=$(echo "$std_output" | grep -v "^$")
std_output=$(echo "$std_output" | sort -V)

_display_text_box ""
