#!/usr/bin/env bash

# Source the script 'common-functions.sh'.
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/common-functions.sh"

_main() {
    local input_files=""
    local output_dir=""

    # Execute initial checks.
    _check_dependencies ""
    input_files=$(_get_files "par_type=file; par_select_mime=image/; par_validate_conflict=true")

    local dependencies=""
    dependencies=$(_get_dependencies "$input_files")
    _check_dependencies "$dependencies"
    _display_wait_box "2"
    output_dir=$(_get_output_dir "par_use_same_dir=true")

    export -f _get_command _run_command

    # Execute the function '_main_task' for each file in parallel.
    _run_task_parallel "$input_files" "$output_dir"
    _display_result_box "$output_dir"
}

_main_task() {
    local input_file=$1
    local output_dir=$2
    local output_file=""

    # Run the main process.
    local command=""
    command=$(_get_command "$input_file")
    _run_command "$input_file" "$command" "$output_dir"
}

_get_dependencies() {
    local input_files=$1
    local dependencies=""

    # Check dependencies for each file.
    for input_file in $input_files; do
        local command=""
        command=$(_get_command "$input_file")

        case $command in
        "convert")
            dependencies+="
                command=convert; pkg_manager=apt; package=imagemagick |
                command=convert; pkg_manager=dnf; package=ImageMagick |
                command=convert; pkg_manager=pacman; package=imagemagick"
            ;;
        "inkscape") dependencies+="command=inkscape" ;;
        esac
        dependencies+=$'\n'
    done

    printf "%s" "$dependencies"
}

_get_command() {
    local input_file=$1
    local command=""

    case "${input_file,,}" in
    *.svg | *.svgz) command="inkscape" ;;
    *) command="convert" ;;
    esac

    printf "%s" "$command"
}

_run_command() {
    local input_file=$1
    local command=$2
    local output_dir=$3
    local output_format="pdf"

    output_file=$(_get_output_filename "$input_file" "$output_dir" "par_extension_opt=replace; par_extension=$output_format")

    # Run the main process.
    case $command in
    "convert")
        std_output=$(convert "$input_file" "$output_file" 2>&1)
        _check_output "$?" "$std_output" "$input_file" "$output_file" || return 1
        ;;
    "inkscape")
        local inkscape_ver=""
        local inkscape_ver_old="1.0"
        inkscape_ver=$(inkscape --version 2>/dev/null | cut -d " " -f 2)
        if [[ "$inkscape_ver" == $(echo -e "$inkscape_ver\n$inkscape_ver_old" |
            sort --version-sort | head -n 1) ]]; then
            # Old Inkscape version.
            std_output=$(inkscape --without-gui --export-area-drawing --file="$input_file" --export-pdf="$output_file" 2>&1)
        else
            # New Inkscape version.
            std_output=$(inkscape --export-area-drawing --export-filename="$output_file" -- "$input_file" 2>&1)
        fi
        _check_output "$?" "$std_output" "$input_file" "$output_file" || return 1
        ;;
    esac
}

_main "$@"
