#!/usr/bin/env bash

# Source the file 'scripts/common-functions'
# shellcheck disable=SC1090
source "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")" | sed -z 's|\(scripts\).*|\1/common-functions|')"

# Initial checks
_check_dependency zenity md5sum
_check_number_files $# 1

# Run the main process
RESULT=$(md5sum "$@")
WIDTH_TEXT=$(echo "$RESULT" | wc -L)
WIDTH_WINDOW=$(($WIDTH_TEXT * 8))
zenity --info --width="$WIDTH_WINDOW" --title "Hash" --text "$RESULT"
