#!/usr/bin/env bash

# Import the script 'common-functions.sh'
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(echo "$SCRIPT_DIR" | grep --only-matching "^.*scripts[^/]*")
source "$ROOT_DIR/common-functions.sh"

# Initial checks
_check_dependencies "md5sum"
_display_wait_box
INPUT_FILES=$(_get_files "$*" "type=file_recursive")

# Run the main process
# shellcheck disable=SC2086
STD_OUTPUT=$(md5sum $INPUT_FILES)

_display_text_box "$STD_OUTPUT"
