#!/usr/bin/env bash

# Import the script 'common-functions.sh'
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(echo "$SCRIPT_DIR" | grep --only-matching "^.*scripts[^/]*")
source "$ROOT_DIR/common-functions.sh"

# Initial checks
_check_dependencies "sha1sum"
_display_wait_box
input_files=$(_get_files "$*" "type=file_recursive")

# Run the main process
# shellcheck disable=SC2086
std_output=$(sha1sum $input_files)

_display_text_box "$std_output"
