#!/usr/bin/env bash

# shellcheck disable=SC2001

# Import the script 'common-functions.sh'
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(echo "$SCRIPT_DIR" | grep --only-matching "^.*scripts[^/]*")
source "$ROOT_DIR/common-functions.sh"

# Initial checks
_check_dependencies ""
_display_wait_box
INPUT_FILES=$(_get_files "$*" "type=file_recursive; mime=text,application; skip_encoding=binary; skip_extension=pdf")

# Run the main process
# shellcheck disable=SC2086
STD_OUTPUT=$(file --separator "//" --no-pad $INPUT_FILES)
STD_OUTPUT=$(echo "$STD_OUTPUT" | sed "s|//.*with CRLF, CR, LF line.*|// CRLF+CR+LF (windows)|")
STD_OUTPUT=$(echo "$STD_OUTPUT" | sed "s|//.*with CRLF, LF line.*|// CRLF+LF (windows)|")
STD_OUTPUT=$(echo "$STD_OUTPUT" | sed "s|//.*with CRLF, CR line.*|// CRLF+CR (windows)|")
STD_OUTPUT=$(echo "$STD_OUTPUT" | sed "s|//.*with CRLF line.*|// CRLF (windows)|")
STD_OUTPUT=$(echo "$STD_OUTPUT" | sed "s|//.*with CR line.*|// CR (mac)|")
STD_OUTPUT=$(echo "$STD_OUTPUT" | sed "s|//.*with CR, LF line.*|// CR+LF (mac)|")
STD_OUTPUT=$(echo "$STD_OUTPUT" | sed "s|//.*no line.*|// (no line)|")
STD_OUTPUT=$(echo "$STD_OUTPUT" | sed "s|//.*text.*|// LF (unix)|")
STD_OUTPUT=$(echo "$STD_OUTPUT" | sed "s|\(.*\)// *\(.*\)|\2: \"\1\"|")
STD_OUTPUT=$(echo "$STD_OUTPUT" | grep "(windows):\|(unix):\|(mac):\|(no line):")
STD_OUTPUT=$(echo "$STD_OUTPUT" | sort -V)

_display_text_box "$STD_OUTPUT"
