#!/usr/bin/env bash

# Source the script 'common-functions.sh'.
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/common-functions.sh"

_main() {
    local input_files=""
    local output_dir=""

    # Execute initial checks.
    _check_dependencies "ffmpeg"
    _display_wait_box
    input_files=$(_get_files "$*" "type:file, mime:audio|video|stream, min_files:2, max_files:2")
    output_dir=$(_get_output_dir)

    _main_task_multiple_files "$input_files" "$output_dir"
    _display_result_box "$output_dir"
}

_main_task_multiple_files() {
    local input_files=$1
    local output_dir=$2
    local output_file=""
    local std_output=""
    local input_file_1=""
    local input_file_2=""

    input_file_1=$(cut -f 1 -d "$FILENAME_SEPARATOR" <<<"$input_files")
    input_file_2=$(cut -f 2 -d "$FILENAME_SEPARATOR" <<<"$input_files")

    # Run the main process.
    output_file="$output_dir/mixed-audio.wav"
    output_file=$(_get_output_file "$output_file" "$output_dir" "")
    std_output=$(ffmpeg -y -i "$input_file_1" -i "$input_file_2" -filter_complex "amix=inputs=2:duration=longest" -- "$output_file" 2>&1)
    _check_result "$?" "$std_output" "" "$output_file" || return 1
}

_main "$@"
