#!/usr/bin/env bash

# Import the script 'common-functions.sh'
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/common-functions.sh"

# Initial checks
_check_dependencies "ffmpeg"
_display_wait_box
input_files=$(_get_files "$*" "type=file; mime=audio,video,stream; min_files=2; max_files=2")
output_dir=$(_get_output_dir)

_task() {
    local input_files=$1
    local output_dir=$2
    local output_file=""
    local std_output=""
    local input_file_1=""
    local input_file_2=""

    input_file_1=$(sed -n 1p <<<"$input_files")
    input_file_2=$(sed -n 2p <<<"$input_files")

    # Run the main process
    output_file="$output_dir/mixed-audio.wav"
    std_output=$(ffmpeg -threads 4 -y -i "$input_file_1" -i "$input_file_2" -filter_complex "amix=inputs=2:duration=longest" -- "$output_file" 2>&1)
    _check_result "$?" "$std_output" "" "$output_file" || return 1
}

_task "$input_files" "$output_dir"
_display_result_box "$output_dir"
