#!/usr/bin/env bash

# Import the script 'common-functions.sh'
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(echo "$SCRIPT_DIR" | grep --only-matching "^.*scripts[^/]*")
source "$ROOT_DIR/common-functions.sh"

# Initial checks
_check_dependencies "gpg"
_display_wait_box
INPUT_FILES=$(_get_files "$*" "type=file")
OUTPUT_DIR=$(_get_output_dir)

TASK_DATA=$(_display_password_box)

_main_task() {
    local INPUT_FILE=$1
    local OUTPUT_DIR=$2
    local OUTPUT_FILE=""
    local STD_OUTPUT=""

    # Run the main process
    OUTPUT_FILE="$OUTPUT_DIR/$INPUT_FILE.asc"
    STD_OUTPUT=$(gpg --batch --yes --symmetric --passphrase "$TASK_DATA" --for-your-eyes-only --armor --s2k-count 1015808 --s2k-digest-algo SHA256 --compress-algo zlib --cipher-algo AES256 --output "$OUTPUT_FILE" "$INPUT_FILE" 2>&1)
    _check_result "$?" "$STD_OUTPUT" "$INPUT_FILE" "$OUTPUT_FILE" || return 1
}

_run_main_task_parallel "$INPUT_FILES" "$OUTPUT_DIR"
_display_result_box "$OUTPUT_DIR"
