#!/usr/bin/env bash

# Import the script 'common-functions.sh'
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
source "${SCRIPT_DIR/%scripts\/*/scripts}/common-functions.sh"

# Initial checks
_check_dependencies "gpg"
_display_wait_box
INPUT_FILES=$(_get_files "$*" "type=file")
OUTPUT_DIR=$PWD

_main_task() {
    local INPUT_FILE=$1
    local OUTPUT_DIR=$2
    local STD_OUTPUT=""
    local KEY_ID=""

    # Get the ID from the key
    KEY_ID=$(gpg --with-colons --import-options show-only --import "$INPUT_FILE" | grep "^fpr" | head -1 | cut -d ':' -f 10)

    # Import the key
    STD_OUTPUT=$(gpg --batch --yes --import "$INPUT_FILE" 2>&1)
    _check_result "$?" "$STD_OUTPUT" "$INPUT_FILE" "" || return 1

    # Set the trust level to 'ultimate'
    STD_OUTPUT=$(echo "$KEY_ID:6:" | gpg --batch --yes --import-ownertrust 2>&1)
    _check_result "$?" "$STD_OUTPUT" "$INPUT_FILE" "" || return 1
}

_run_main_task_parallel "$INPUT_FILES" "$OUTPUT_DIR"
_display_result_box "$OUTPUT_DIR"
