#!/usr/bin/env bash

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
# shellcheck source=/dev/null
source "${SCRIPT_DIR%/*}/common-functions"

# Initial checks
_check_dependencies gpg zenity || exit 1
INPUT_FILES=$(_get_files "$*" "" "1" "" "") || exit 1
DATA=$(_display_password_box) || exit 1
OUTPUT_DIR=$(_get_output_dir) || exit 1

_main_task() {
    local FILE=$1
    local OUTPUT_DIR=$2
    local OUTPUT_FILE
    local STD_OUTPUT
    local EXIT_CODE

    OUTPUT_FILE="$OUTPUT_DIR/$FILE.asc"
    STD_OUTPUT=$(gpg --batch --yes --symmetric --passphrase "$DATA" --for-your-eyes-only --armor --s2k-count 1015808 --s2k-digest-algo SHA256 --compress-algo zlib --cipher-algo AES256 --output "$OUTPUT_FILE" "$FILE" 2>&1)
    EXIT_CODE=$?
    _log_error_result "$FILE" "$STD_OUTPUT" "$OUTPUT_DIR" "$EXIT_CODE" "$OUTPUT_FILE"
}

_run_parallel_tasks "$INPUT_FILES"
_display_result_tasks "$OUTPUT_DIR"
