#!/usr/bin/env bash
# install_keyboard_shortcut=<Control><Alt>4

# Source the script 'common-functions.sh'.
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/common-functions.sh"

_main() {
    local input_files=""
    local output_dir=""

    # Execute initial checks.
    _check_dependencies ""
    _display_wait_box "2"
    input_files=$(_get_files "par_type=file; par_recursive=true; par_get_pwd=true; par_select_mime='text/|application/json'")

    # Execute the function '_main_task' for each file in parallel.
    _run_task_parallel "$input_files" "$output_dir"

    local std_output=""
    std_output=$(_storage_text_read_all)
    std_output=$(_text_sort "$std_output")

    _display_list_box "$std_output" "--column=Encoding;--column=File"
}

_main_task() {
    local input_file=$1
    local output_dir=$2
    local std_output=""
    local file_encoding=""
    file_encoding=$(_get_file_encoding "$input_file")

    if [[ -z "$file_encoding" ]]; then
        return
    fi

    # Run the main process.
    std_output="$file_encoding$FIELD_SEPARATOR$input_file"
    std_output=$(_text_remove_pwd "$std_output")

    _storage_text_write_ln "$std_output"
}

_main "$@"
