#!/usr/bin/env bash

# Source the file 'scripts/common-functions'
# shellcheck disable=SC1090
source "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")" | sed 's|\(scripts\).*|\1/common-functions|')"

# Initial checks
INPUT_FILES=$(_check_files "$*" "" "1" "" "d") || exit 1
OUTPUT_DIR="$PWD"

for FILE in $INPUT_FILES; do
    # Run the main process
    STD_OUTPUT=""
    if [ -f "$FILE" ]; then
        STD_OUTPUT="$(chmod 600 "$FILE" 2>&1)"
    elif [ -d "$FILE" ]; then
        STD_OUTPUT="$(chmod 700 "$FILE" 2>&1)"
    fi
    EXIT_CODE=$?

    # Check the return and log the error
    if [ "$EXIT_CODE" -ne 0 ]; then
        _log_error "$FILE" "$STD_OUTPUT" "$OUTPUT_DIR"
    fi
done

_display_result ""
