#!/usr/bin/env bash

# Source the file 'scripts/common-functions'
# shellcheck disable=SC1090
source "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")" | sed 's|\(scripts\).*|\1/common-functions|')"

# Initial checks
INPUT_FILES=$(_get_files "$*" "" "1" "" "R") || exit 1
OUTPUT_DIR="$PWD" || exit 1

for FILE in $INPUT_FILES; do
    # Run the main process
    STD_OUTPUT=""
    if [ -f "$FILE" ]; then
        STD_OUTPUT="$(chmod 600 "$FILE" 2>&1)"
    elif [ -d "$FILE" ]; then
        STD_OUTPUT="$(chmod 700 "$FILE" 2>&1)"
    fi
    EXIT_CODE=$?

    _log_result_error "$FILE" "$STD_OUTPUT" "$OUTPUT_DIR" "$EXIT_CODE" "$OUTPUT_FILE"
done

_display_result "$OUTPUT_DIR"
