#!/usr/bin/env bash

# Source the file 'scripts/common-functions'
# shellcheck disable=SC1090
source "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")" | sed 's|\(scripts\).*|\1/common-functions|')"

# Initial checks
INPUT_FILES=$(_get_files "$*" "" "1" "" "R") || exit 1
OUTPUT_DIR="$PWD"

_run_task() {
    local FILE="$1"
    local OUTPUT_DIR="$2"
    local STD_OUTPUT=""
    local EXIT_CODE=0

    STD_OUTPUT=""
    if [ -f "$FILE" ]; then
        STD_OUTPUT="$(chmod 644 "$FILE" 2>&1)"
    elif [ -d "$FILE" ]; then
        STD_OUTPUT="$(chmod 755 "$FILE" 2>&1)"
    fi
    EXIT_CODE=$?
    _log_result_error "$FILE" "$STD_OUTPUT" "$OUTPUT_DIR" "$EXIT_CODE" ""
}

_run_parallel_task "$INPUT_FILES"
_display_result_task "$OUTPUT_DIR"
