#!/usr/bin/env bash

# Import the script 'common-functions.sh'
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/common-functions.sh"

# Initial checks
_display_wait_box
input_files=$(_get_files "$*" "type=all")

_main_task() {
    local input_file=$1
    local output_dir=$2
    local std_output=""

    # Run the main process
    if [[ -f "$input_file" ]]; then
        std_output=$(chmod --recursive 644 "$input_file" 2>&1)
    elif [[ -d "$input_file" ]]; then
        std_output=$(chmod --recursive 755 "$input_file" 2>&1)
    fi
    _check_result "$?" "$std_output" "$input_file" "" || return 1
}

_run_main_task_parallel "$input_files" ""
_display_result_box ""
