#!/usr/bin/env bash

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
# shellcheck source=/dev/null
source "${SCRIPT_DIR%/*}/common-functions"

# Initial checks
INPUT_FILES=$(_get_files "$*" "" "1" "" "R") || exit 1
OUTPUT_DIR="$PWD"

_main_task() {
    local FILE=$1
    local OUTPUT_DIR=$2
    local STD_OUTPUT
    local EXIT_CODE

    if [ -f "$FILE" ]; then
        STD_OUTPUT=$(chmod 644 "$FILE" 2>&1)
    elif [ -d "$FILE" ]; then
        STD_OUTPUT=$(chmod 755 "$FILE" 2>&1)
    fi
    EXIT_CODE=$?
    _log_error_result "$FILE" "$STD_OUTPUT" "$OUTPUT_DIR" "$EXIT_CODE" ""
}

_run_parallel_tasks "$INPUT_FILES"
_display_result_tasks "$OUTPUT_DIR"
