#!/usr/bin/env bash

# Import the script 'common-functions.sh'
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
source "${SCRIPT_DIR/%scripts\/*/scripts}/common-functions.sh"

# Initial checks
_display_wait_box
INPUT_FILES=$(_get_files "$*" "type=all_recursive")

# Run the main process
# shellcheck disable=SC2086
STD_OUTPUT=$(stat -c "%a %U %G %F: \"%n\"" $INPUT_FILES)
STD_OUTPUT=$(echo "$STD_OUTPUT" | sort -V)

_display_text_box "$STD_OUTPUT"
