#!/usr/bin/env bash

# Import the script 'common-functions.sh'
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/common-functions.sh"

# Initial checks
_display_wait_box
input_files=$(_get_files "$*" "type=all_recursive")

# Run the main process
# shellcheck disable=SC2086
std_output=$(stat -c "%a %U %G %F: \"%n\"" $input_files)
std_output=$(sort -V <<<"$std_output")

_display_text_box "$std_output"
