#!/usr/bin/env bash

# Source the script 'common-functions.sh'.
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/common-functions.sh"

_main() {
    local input_files=""
    local output_dir=""

    # Execute initial checks.
    _check_dependencies ""
    _display_wait_box "2"
    input_files=$(_get_files "par_type=all")

    # Execute the function '_main_task' for each file in parallel.
    _run_task_parallel "$input_files" "$output_dir"
    _display_result_box ""
}

_main_task() {
    local input_file=$1
    local output_dir=$2
    local std_output=""
    local new_pemission=""

    # Run the main process.
    new_pemission=$(printf "%04o" "$((0666 - $(umask)))")
    std_output=$(find "$input_file" -type f ! -path "$IGNORE_FIND_PATH" -exec chmod "$new_pemission" -- {} \+ 2>&1)
    _check_output "$?" "$std_output" "$input_file" "" || return 1

    new_pemission=$(printf "%04o" "$((0777 - $(umask)))")
    std_output=$(find "$input_file" -type d ! -path "$IGNORE_FIND_PATH" -exec chmod "$new_pemission" -- {} \+ 2>&1)
    _check_output "$?" "$std_output" "$input_file" "" || return 1
}

_main "$@"
