#!/usr/bin/env bash

# Source the script 'common-functions.sh'.
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/common-functions.sh"

_main() {
    local input_files=""
    local output_dir=""

    # Execute initial checks.
    _check_dependencies "7za(apt:p7zip-full,pacman:p7zip,dnf:p7zip)"
    _display_wait_box
    input_files=$(_get_files "type:all, validate_conflict:true")
    output_dir=$(_get_output_dir "use_same_dir:true")

    # Execute the function '_main_task' for each file in parallel.
    _run_task_parallel "$input_files" "$output_dir"
    _display_result_box "$output_dir"
}

_main_task() {
    local input_file=$1
    local output_dir=$2
    local output_file=""
    local std_output=""

    # Run the main process.
    output_file=$(_get_output_file "$input_file" "$output_dir" "extension_option:new, extension:7z")
    if [[ -d "$input_file" ]]; then
        cd -- "$input_file" || return 1
        std_output=$(7za a -mx9 "$output_file" -- . 2>&1)
    else
        local input_file_relative=""
        input_file_relative=$(_text_remove_pwd "$input_file")
        std_output=$(7za a -mx9 "$output_file" -- "$input_file_relative" 2>&1)
    fi
    _check_result "$?" "$std_output" "$input_file" "$output_file" || return 1
}

_main "$@"
