#!/usr/bin/env bash

# Source the script '.common-functions.sh'.
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/.common-functions.sh"

_main() {
    local input_files=""
    local output_dir=""

    # Execute initial checks.
    _check_dependencies ""
    _display_wait_box "2"
    input_files=$(_get_files "par_type=file; par_recursive=true")

    local output_file=""
    local options=""
    if (($(_get_items_count "$input_files") == 1)); then
        local file_1=""
        file_1=$(cut -d "$FIELD_SEPARATOR" -f 1 <<<"$input_files")
        file_1=$(basename -- "$file_1")
        options+=$file_1
        options+=".sha256"
        options+="$FIELD_SEPARATOR"
    fi
    options+="sha256sum.txt"
    options+="$FIELD_SEPARATOR"
    options+="checksums.sha256"
    options+="$FIELD_SEPARATOR"
    options+="SHA256SUMS"

    output_file=$(_display_checklist_box_simple \
        "$options" \
        "Select output checksum file" \
        "Select output checksum file from the list below." \
        "Filename" "true" "true")

    output_dir=$(_get_output_dir "par_use_same_dir=true")

    # Execute the function '_main_task' for each file in parallel.
    _run_task_parallel "$input_files" "$output_dir"

    output_file=$(_get_output_filename "$output_file" "$output_dir" "par_extension_opt=preserve")

    local std_output=""
    std_output=$(_storage_text_read_all)
    std_output=$(_text_sort "$std_output")
    # shellcheck disable=SC2001
    std_output=$(sed "s|\(.*\)$FIELD_SEPARATOR\(.*\)|\2  \1|g" <<<"$std_output")
    printf "%s\n" "$std_output" >"$output_file"

    _display_result_box "$output_dir"
}

_main_task() {
    local input_file=$1
    local output_dir=$2
    local std_output=""

    # Run the main process.
    std_output=$(sha256sum -- "$input_file" 2>/dev/null)
    if [[ -z "$std_output" ]]; then
        return
    fi

    std_output=$(_text_remove_pwd "$std_output")

    # shellcheck disable=SC2001
    std_output=$(sed "s|\([^ ]*\)\s*\(.*\)|\2$FIELD_SEPARATOR\1|g" <<<"$std_output")

    _storage_text_write_ln "$std_output"
}

_main "$@"
