#!/usr/bin/env bash

# Import the script 'common-functions.sh'
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
source "${SCRIPT_DIR/%scripts\/*/scripts}/common-functions.sh"

# Initial checks
_check_dependencies "convert(imagemagick)"
_display_wait_box
INPUT_FILES=$(_get_files "$*" "type=file; mime=image")
OUTPUT_DIR=$(_get_output_dir)

_task() {
    local INPUT_FILES=$1
    local OUTPUT_DIR=$2
    local OUTPUT_FILE=""
    local STD_OUTPUT=""

    # Run the main process
    OUTPUT_FILE="$OUTPUT_DIR/image.pdf"
    # shellcheck disable=SC2086
    STD_OUTPUT=$(convert $INPUT_FILES "$OUTPUT_FILE" 2>&1)
    _check_result "$?" "$STD_OUTPUT" "" "$OUTPUT_FILE" || return 1
}

_task "$INPUT_FILES" "$OUTPUT_DIR"
_display_result_box "$OUTPUT_DIR"
