#!/usr/bin/env bash

# Import the script 'common-functions.sh'
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(echo "$SCRIPT_DIR" | grep --only-matching "^.*scripts[^/]*")
source "$ROOT_DIR/common-functions.sh"

# Initial checks
_check_dependencies "convert(imagemagick)"
_display_wait_box
input_files=$(_get_files "$*" "type=file; mime=image")
output_dir=$(_get_output_dir)

_task() {
    local input_files=$1
    local output_dir=$2
    local output_file=""
    local std_output=""

    # Run the main process
    output_file="$output_dir/combined-images.pdf"
    # shellcheck disable=SC2086
    std_output=$(convert $input_files "$output_file" 2>&1)
    _check_result "$?" "$std_output" "" "$output_file" || return 1
}

_task "$input_files" "$output_dir"
_display_result_box "$output_dir"
