#!/usr/bin/env bash

# Source the script '.common-functions.sh'.
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/.common-functions.sh"

_main() {
    local input_files=""
    local output_dir=""

    # Execute initial checks.
    _check_dependencies ""
    input_files=$(_get_files "par_type=file; par_select_extension='bmp|csv|doc|docx|epub|fb2|fodf|fodg|fodp|fods|fodt|gfm|gif|htm|html|jpeg|jpg|json|markdown|md|odf|odg|odp|ods|odt|opml|org|png|ppt|pptx|rst|rtf|svg|svgz|tex|tif|tiff|txt|webp|xls|xlsx'")

    local dependencies=""
    dependencies=$(_get_dependencies "$input_files")
    _check_dependencies "$dependencies"
    _display_wait_box "2"
    output_dir=$(_get_output_dir "par_use_same_dir=true")

    export -f _get_command _run_command

    # Execute the function '_main_task' for each file in parallel.
    _run_task_parallel "$input_files" "$output_dir"
    _display_result_box "$output_dir"
}

_main_task() {
    local input_file=$1
    local output_dir=$2
    local output_file=""
    local command=""

    # Run the main process.
    command=$(_get_command "$input_file")
    _run_command "$input_file" "$command" "$output_dir"
}

_get_dependencies() {
    local input_files=$1
    local dependencies=""

    # Check dependencies for each file.
    local input_file=""
    for input_file in $input_files; do
        local command=""
        command=$(_get_command "$input_file")

        case $command in
        "convert")
            if ! _command_exists "magick"; then
                dependencies+="convert"
            fi
            ;;
        "inkscape") dependencies+="inkscape" ;;
        "latexmk") dependencies+="latexmk texlive" ;;
        "libreoffice_calc")
            if ! _command_exists "libreoffice.calc" &&
                ! _command_exists "localc" &&
                ! _command_exists "libreoffice-calc"; then
                dependencies+="localc"
            fi
            ;;
        "libreoffice_impress")
            if ! _command_exists "libreoffice.impress" &&
                ! _command_exists "loimpress" &&
                ! _command_exists "libreoffice-impress"; then
                dependencies+="loimpress"
            fi
            ;;
        "libreoffice_writer")
            if ! _command_exists "libreoffice.writer" &&
                ! _command_exists "lowriter" &&
                ! _command_exists "libreoffice-writer"; then
                dependencies+="lowriter"
            fi
            ;;
        "pandoc_latex") dependencies+="pandoc texlive" ;;
        "pandoc") dependencies+="pandoc" ;;
        esac
        dependencies+=$'\n'
    done

    printf "%s" "$dependencies"
}

_get_command() {
    local input_file=$1
    local command=""

    case "${input_file,,}" in
    *.bmp | *.gif | *.jpeg | *.jpg | *.png | *.tif | *.tiff | *.webp) command="convert" ;;
    *.doc | *.docx) command="libreoffice_writer" ;;
    *.htm | *.html) command="libreoffice_writer" ;;
    *.md | *.markdown) command="pandoc_latex" ;;
    *.odf | *.fodf) command="libreoffice_writer" ;;
    *.odg | *.fodg) command="libreoffice_impress" ;;
    *.odp | *.fodp) command="libreoffice_impress" ;;
    *.ods | *.fods) command="libreoffice_calc" ;;
    *.odt | *.fodt) command="libreoffice_writer" ;;
    *.ppt | *.pptx) command="libreoffice_impress" ;;
    *.rtf) command="libreoffice_writer" ;;
    *.svg | *.svgz) command="inkscape" ;;
    *.tex) command="latexmk" ;;
    *.txt) command="pandoc_latex" ;;
    *.xls | *.xlsx) command="libreoffice_calc" ;;
    *) command="pandoc" ;;
    esac

    printf "%s" "$command"
}

_run_command() {
    local input_file=$1
    local command=$2
    local output_dir=$3
    local output_format="pdf"

    output_file=$(_get_output_filename "$input_file" "$output_dir" "par_extension_opt=replace; par_extension=$output_format")

    # Run the main process.
    case $command in
    "convert")
        std_output=$(_cmd_magick_convert "$input_file" "$output_file" 2>&1)
        _check_output "$?" "$std_output" "$input_file" "$output_file" || return 1
        ;;
    "inkscape")
        local inkscape_ver=""
        local inkscape_ver_old="1.0"
        inkscape_ver=$(inkscape --version 2>/dev/null | cut -d " " -f 2)
        if printf "%s\n%s" "$inkscape_ver" "$inkscape_ver_old" |
            sort --version-sort | head -n 1 |
            grep --quiet --line-regexp "$inkscape_ver"; then
            # Old Inkscape version.
            std_output=$(inkscape --without-gui --export-area-drawing --file="$input_file" --export-pdf="$output_file" 2>&1)
        else
            # New Inkscape version.
            std_output=$(inkscape --export-area-drawing --export-filename="$output_file" -- "$input_file" 2>&1)
        fi
        _check_output "$?" "$std_output" "$input_file" "$output_file" || return 1
        ;;
    "latexmk")
        # Use a local temporary directory to work.
        local basename=""
        local temp_dir_local=""
        local temp_output_file=""
        basename=$(basename -- "$input_file")             # Remove the path.
        basename=$(_strip_filename_extension "$basename") # Remove the extension.
        temp_dir_local=$(_make_temp_dir_local "$output_dir" ".$basename")

        temp_output_file=$(_get_output_filename "$input_file" "$temp_dir_local" "par_extension_opt=replace; par_extension=$output_format")

        std_output=$(latexmk -f -pdf -interaction=nonstopmode -output-directory="$temp_dir_local" "$input_file" 2>&1)
        _check_output "$?" "$std_output" "$input_file" "$temp_output_file" || return 1

        _move_file "rename" "$temp_output_file" "$output_file" || return 1

        # Remove the temporary directory (local directory).
        rm -rf -- "$temp_dir_local"
        ;;
    "libreoffice_calc" | "libreoffice_impress" | "libreoffice_writer")
        # Use a local temporary directory to work.
        local basename=""
        local temp_dir_local=""
        local temp_output_file=""
        basename=$(basename -- "$input_file")             # Remove the path.
        basename=$(_strip_filename_extension "$basename") # Remove the extension.
        temp_dir_local=$(_make_temp_dir_local "$output_dir" ".$basename")

        # NOTE: Workaround to fix the bug 37531 in LibreOffice.
        # See the: https://bugs.documentfoundation.org/show_bug.cgi?id=37531
        local temp_dir=""
        temp_dir=$(_make_temp_dir)

        # NOTE: LibreOffice does not support '--' in the command line.
        # NOTE: LibreOffice does not support defining the output file manually.
        std_output=$(libreoffice --headless --convert-to "$output_format" "-env:UserInstallation=file://$temp_dir" --outdir "$temp_dir_local" "$input_file" 2>&1)

        # Remove the temporary directory.
        rm -rf -- "$temp_dir"

        temp_output_file=$(find "$temp_dir_local" -type f -name "*.$output_format" -print -quit 2>/dev/null)
        _move_file "rename" "$temp_output_file" "$output_file"

        # Remove the temporary directory (local directory).
        rm -rf -- "$temp_dir_local"

        _check_output "$?" "$std_output" "$input_file" "$output_file" || return 1
        ;;
    "pandoc_latex")
        std_output=$(pandoc -V "geometry:margin=1.5cm" -V "geometry:a4paper" -V "fontfamily:charter,inconsolata" --standalone -o "$output_file" -- "$input_file" 2>&1)
        _check_output "$?" "$std_output" "$input_file" "$output_file" || return 1
        ;;
    "pandoc")
        std_output=$(pandoc --standalone -o "$output_file" -- "$input_file" 2>&1)
        _check_output "$?" "$std_output" "$input_file" "$output_file" || return 1
        ;;
    esac
}

_main "$@"
