#!/usr/bin/env bash

# Source the script '.common-functions.sh'.
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/.common-functions.sh"

_main() {
    local input_files=""
    local std_output=""

    # Execute initial checks.
    _check_dependencies ""
    _display_wait_box
    input_files=$(_get_files "par_type=all")

    # Run the main process.
    # shellcheck disable=SC2086
    std_output=$(find -L $input_files \
        ! -path "$IGNORE_FIND_PATH" \
        -type f -links +1 -printf "%i$FIELD_SEPARATOR%p\n" 2>/dev/null)
    std_output=$(_text_remove_pwd "$std_output")
    std_output=$(_text_sort "$std_output")

    # shellcheck disable=SC2155
    local item_name="$(_i18n 'hard links')"
    _display_list_box "$std_output" "par_columns='--column:Inode,--column:File'; par_item_name=$item_name; par_action=open_location; par_checkbox=true"
}

_main "$@"
