#!/usr/bin/env bash

# Source the script 'common-functions.sh'.
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/common-functions.sh"

_main() {
    local input_files=""

    # Execute initial checks.
    _check_dependencies ""
    _display_wait_box "2"
    input_files=$(_get_files "par_type=file; par_recursive=true; par_get_pwd=true; par_select_extension=pdf")

    # Execute the function '_main_task' for each file in parallel.
    _run_task_parallel "$input_files" ""

    local std_output=""
    std_output=$(_storage_text_read_all)
    std_output=$(_text_sort "$std_output")

    _display_list_box "$std_output" "par_columns='--column:File'; par_item_name=PDFs; par_action=open_location; par_checkbox=true"
}

_main_task() {
    local input_file=$1
    local output_dir=$2

    # Run the main process.
    if grep -z -a -m1 --quiet "/Subtype\s*\(/Caret\|/Circle\|/FileAttachment\|/FreeText\|/Highlight\|/Ink\|/Line\|/Movie\|/Polygon\|/PolyLine\|/Popup\|/Printermark\|/Screen\|/Sound\|/Square\|/Squiggly\|/Stamp\|/StrikeOut\|/Text\|/Underline\|/Watermark\)" "$input_file"; then
        _storage_text_write_ln "$(_text_remove_pwd "$input_file")"
    fi
}

_main "$@"
