#!/usr/bin/env bash

# Source the file 'scripts/common-functions'
# shellcheck disable=SC1090
source "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")" | sed 's|\(scripts\).*|\1/common-functions|')"

# Initial checks
_check_dependencies convert
INPUT_FILES=$(_get_files "$*" "" "1" "" "") || exit 1
OUTPUT_DIR=$(_get_output_dir)

for FILE in $INPUT_FILES; do
    # Run the main process
    OUTPUT_FILE="$OUTPUT_DIR/$(_get_filename_without_extension "$FILE").png"
    STD_OUTPUT="$(convert -transparent black -fuzz 5% "$FILE" "$OUTPUT_FILE" 2>&1)"
    EXIT_CODE=$?

    # Check the return and log the error
    if [ "$EXIT_CODE" -ne 0 ]; then
        _log_error "$FILE" "$STD_OUTPUT" "$OUTPUT_DIR"
    fi
done

_display_result "$OUTPUT_DIR"
