#!/usr/bin/env bash

# Source the file 'scripts/common-functions'
# shellcheck disable=SC1090
source "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")" | sed 's|\(scripts\).*|\1/common-functions|')"

# Initial checks
_check_dependencies mp3val || exit 1
INPUT_FILES=$(_get_files "$*" "audio/mpeg" "1" "" "") || exit 1
OUTPUT_DIR="$PWD"

_main_task() {
    local FILE="$1"
    local OUTPUT_DIR="$2"
    local EXIT_CODE=0

    mp3val -si -f "$FILE"
    EXIT_CODE=$?
    _log_error_result "$FILE" "" "$OUTPUT_DIR" "$EXIT_CODE" ""
}

_run_parallel_tasks "$INPUT_FILES"
_display_result_tasks "$OUTPUT_DIR"
