#!/usr/bin/env bash

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
# shellcheck source=/dev/null
source "${SCRIPT_DIR%/*}/common-functions"

# Initial checks
_check_dependencies ffmpeg || exit 1
INPUT_FILES=$(_get_files "$*" "audio;video" "2" "2" "") || exit 1
OUTPUT_DIR=$(_get_output_dir) || exit 1

FILE_1=$(echo "$INPUT_FILES" | sed -n 1p)
FILE_2=$(echo "$INPUT_FILES" | sed -n 2p)

OUTPUT_FILE="$OUTPUT_DIR/mix.wav"
STD_OUTPUT=$(ffmpeg -threads 4 -y -i "$FILE_1" -i "$FILE_2" -filter_complex "amix=inputs=2:duration=longest" "$OUTPUT_FILE" 2>&1)
EXIT_CODE=$?
_log_error_result "$FILE" "$STD_OUTPUT" "$OUTPUT_DIR" "$EXIT_CODE" "$OUTPUT_FILE"

_display_result_tasks "$OUTPUT_DIR"
