#!/usr/bin/env bash

# Source the script 'common-functions.sh'.
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/common-functions.sh"

_main() {
    local input_files=""
    local output_dir=""

    # Execute initial checks.
    _check_dependencies "
        command=lp; pkg_manager=apt; package=cups-client |
        command=lp; pkg_manager=dnf; package=cups-client |
        command=lp; pkg_manager=pacman; package=cups |
        command=lp; pkg_manager=zypper; package=cups"
    _display_wait_box "2"
    input_files=$(_get_files "par_type=file")

    # Execute the function '_main_task' for each file in parallel.
    _run_task_parallel "$input_files" "$output_dir"
    _display_result_box ""
}

_main_task() {
    local input_file=$1
    local output_dir=$2
    local std_output=""

    # Run the main process.
    std_output=$(lp -o media=Legal "$input_file" 2>&1)
    _check_output "$?" "$std_output" "$input_file" "" || return 1
}

_main "$@"
