#!/usr/bin/env bash

# Source the script 'common-functions.sh'.
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/common-functions.sh"

_main() {
    local input_files=""

    # Execute initial checks.
    _check_dependencies "findimagedupes"
    _display_wait_box
    input_files=$(_get_files "par_type=file; par_recursive=true; par_select_mime=image/")

    # Get the installed image viewer.
    local image_viewer=""
    if _command_exists "eog"; then
        image_viewer="eog"
    elif _command_exists "loupe"; then
        image_viewer="loupe"
    else
        _check_dependencies "eog"
        image_viewer="eog"
    fi

    # Run the main process.
    # shellcheck disable=SC2086
    findimagedupes --recurse --threshold=85% --program="$(which "$image_viewer")" -- $input_files 2>/dev/null
    _display_result_box ""
}

_main "$@"
