#!/usr/bin/env bash
# install_keyboard_shortcut=<Control><Alt>Z

# Source the script '.common-functions.sh'.
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/.common-functions.sh"

_main() {
    local input_files=""
    local output_dir=""

    # Execute initial checks.
    if ! _command_exists "zip" && ! _command_exists "bsdtar"; then
        _check_dependencies "7za"
    fi
    _display_wait_box
    input_files=$(_get_files "par_type=all")
    output_dir=$(_get_output_dir "par_use_same_dir=true")

    # Execute the function '_main_task' for each file in parallel.
    _run_task_parallel "$input_files" "$output_dir"
    _display_result_box "$output_dir"
}

_main_task() {
    local input_file=$1
    local output_dir=$2
    local output_file=""
    local std_output=""

    output_file=$(_get_output_filename "$input_file" "$output_dir" "par_extension_opt=replace; par_extension=zip")

    # Run the main process.
    if [[ -d "$input_file" ]]; then
        # Check if the directory is empty.
        if _is_directory_empty "$input_file"; then
            local msg=""
            msg="The directory is empty."
            _log_error "$msg" "$input_file" "" "$output_file"
            return 1
        fi

        # Change to the directory to perform compression.
        _directory_push "$input_file" || return 1

        # Check for available compression tools and compress the directory accordingly.
        if _command_exists "7za"; then
            std_output=$(7za a -snl "$output_file" -- . 2>&1)
        elif _command_exists "bsdtar"; then
            std_output=$(bsdtar --strip-components 1 -a -cf "$output_file" -- . 2>&1)
        elif _command_exists "zip"; then
            std_output=$(zip --symlinks --quiet --recurse-paths "$output_file" -- . 2>&1)
        fi
    else
        # If the input is a file, change to its parent directory.
        _directory_push "$(_get_filename_dir "$input_file")" || return 1

        # Extract the base name of the input file for compression.
        local input_file_basename=""
        input_file_basename=$(basename -- "$input_file")

        # Check for available compression tools and compress the file accordingly.
        if _command_exists "7za"; then
            std_output=$(7za a -snl "$output_file" -- "$input_file_basename" 2>&1)
        elif _command_exists "bsdtar"; then
            std_output=$(bsdtar -a -cf "$output_file" -- "$input_file_basename" 2>&1)
        elif _command_exists "zip"; then
            std_output=$(zip --symlinks --quiet --recurse-paths "$output_file" -- "$input_file_basename" 2>&1)
        fi
    fi
    _check_output "$?" "$std_output" "$input_file" "$output_file" || return 1
    _directory_pop || return 1
}

_main "$@"
