#!/usr/bin/env bash

# Source the script 'common-functions.sh'.
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/common-functions.sh"

_main() {
    local input_files=""
    local output_dir=""

    # Execute initial checks.
    _command_exists "bsdtar" || _check_dependencies "
        command=7za; pkg_manager=apt; package=p7zip-full |
        command=7za; pkg_manager=dnf; package=p7zip |
        command=7za; pkg_manager=pacman; package=p7zip |
        command=7za; pkg_manager=zypper; package=p7zip"
    _display_wait_box "2"
    input_files=$(_get_files "par_type=all")
    output_dir=$(_get_output_dir "par_use_same_dir=true")

    # Execute the function '_main_task' for each file in parallel.
    _run_task_parallel "$input_files" "$output_dir"
    _display_result_box "$output_dir"
}

_main_task() {
    local input_file=$1
    local output_dir=$2
    local output_file=""
    local std_output=""

    # Run the main process.
    output_file=$(_get_output_filename "$input_file" "$output_dir" "par_extension_opt=replace; par_extension=7z")
    if [[ -d "$input_file" ]]; then
        cd -- "$input_file" || return 1

        if _command_exists "7za"; then
            std_output=$(7za a -mx9 "$output_file" -- . 2>&1)
        elif _command_exists "bsdtar"; then
            std_output=$(bsdtar --strip-components 1 -a -cf "$output_file" -- . 2>&1)
        fi
    else
        cd -- "$(_get_filename_dir "$input_file")" || return 1
        local input_file_basename=""
        input_file_basename=$(basename -- "$input_file")

        if _command_exists "7za"; then
            std_output=$(7za a -mx9 "$output_file" -- "$input_file_basename" 2>&1)
        elif _command_exists "bsdtar"; then
            std_output=$(bsdtar -a -cf "$output_file" -- "$input_file_basename" 2>&1)
        fi
    fi
    _check_output "$?" "$std_output" "$input_file" "$output_file" || return 1
}

_main "$@"
