#!/usr/bin/env bash

# Source the file 'scripts/common-functions'
# shellcheck disable=SC1090
source "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")" | sed 's|\(scripts\).*|\1/common-functions|')"

# Initial checks
_check_dependency 7z
INPUT_FILES=$(_check_files "$*" "" "1" "" "d") || exit 1
OUTPUT_DIR="$PWD"

# Run the main process
OUTPUT_FILE="$(pwd | sed "s#.*/##").7z"
# shellcheck disable=SC2086
STD_OUTPUT="$(7z a -mx9 "$OUTPUT_FILE" $INPUT_FILES 2>&1)"
EXIT_CODE=$?

# Check the return and log the error
if [ "$EXIT_CODE" -ne 0 ]; then
    _log_error "$FILE" "$STD_OUTPUT" "$OUTPUT_DIR"
fi

_display_result "$OUTPUT_DIR"
