#!/usr/bin/env bash

# Source the script 'common-functions.sh'.
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/common-functions.sh"

_main() {
    local input_files=""
    local output_dir=""
    local input_file=""
    local show_wait_box=true

    # Execute initial checks.
    _check_dependencies ""
    input_files=$(_get_files "par_type=file")

    # Check dependencies for each file type.
    local dependencies=""
    for input_file in $input_files; do
        case $(_get_command_use "$input_file") in
        "_unknown_")
            dependencies+="command=unar; pkg_manager=apt | command=unar; pkg_manager=dnf | command=unar; pkg_manager=pacman; package=unarchiver"
            dependencies+=$'\n'
            dependencies+="command=7za; pkg_manager=apt; package=p7zip-full | command=7za; pkg_manager=dnf; package=p7zip | command=7za; pkg_manager=pacman; package=p7zip"
            ;;
        "7za")
            _command_exists "bsdtar" && continue
            _command_exists "unar" && continue
            dependencies+="command=7za; pkg_manager=apt; package=p7zip-full | command=7za; pkg_manager=dnf; package=p7zip | command=7za; pkg_manager=pacman; package=p7zip"
            ;;
        "7za+password")
            show_wait_box=false
            dependencies+="command=7za; pkg_manager=apt; package=p7zip-full | command=7za; pkg_manager=dnf; package=p7zip | command=7za; pkg_manager=pacman; package=p7zip"
            ;;
        "ar") dependencies+="command=ar; package=binutils" ;;
        "bzip2")
            _command_exists "bsdtar" && continue
            _command_exists "unar" && continue
            _command_exists "7za" && continue
            dependencies+="command=bzip2"
            ;;
        "cpio")
            _command_exists "bsdtar" && continue
            _command_exists "unar" && continue
            dependencies+="command=cpio"
            ;;
        "gpg") dependencies+="command=gpg; pkg_manager=apt | command=gpg; pkg_manager=dnf; package=gnupg2 | command=gpg; pkg_manager=pacman; package=gnupg" ;;
        "gzip" | "compress")
            _command_exists "bsdtar" && continue
            _command_exists "unar" && continue
            _command_exists "7za" && continue
            dependencies+="command=gzip"
            ;;
        "lha")
            _command_exists "unar" && continue
            dependencies+="command=lha; package=lhasa"
            ;;
        "lrzip") dependencies+="command=lrzip" ;;
        "lz4") dependencies+="command=lz4" ;;
        "lzip") dependencies+="command=lzip" ;;
        "lzop") dependencies+="command=lzop" ;;
        "tar")
            _command_exists "bsdtar" && continue
            _command_exists "unar" && continue
            _command_exists "7za" && continue
            dependencies+="command=tar"
            ;;
        "tar+bzip2")
            _command_exists "bsdtar" && continue
            _command_exists "unar" && continue
            _command_exists "7za" && continue
            dependencies+="command=tar | command=bzip2"
            ;;
        "tar+gzip" | "tar+compress")
            _command_exists "bsdtar" && continue
            _command_exists "unar" && continue
            _command_exists "7za" && continue
            dependencies+="command=tar | command=gzip"
            ;;
        "tar+lrzip") dependencies+="command=lrztar; package=lrzip" ;;
        "tar+lz4") dependencies+="command=tar | command=lz4" ;;
        "tar+lzip") dependencies+="command=tar | command=lzip" ;;
        "tar+lzop") dependencies+="command=tar | command=lzop" ;;
        "tar+xz" | "tar+lzma")
            _command_exists "bsdtar" && continue
            _command_exists "unar" && continue
            _command_exists "7za" && continue
            dependencies+="command=tar | command=xz; pkg_manager=apt; package=xz-utils | command=xz; pkg_manager=dnf | command=xz; pkg_manager=pacman"
            ;;
        "tar+zstd") dependencies+="command=tar | command=zstd" ;;
        "unar") dependencies+="command=unar; pkg_manager=apt | command=unar; pkg_manager=dnf | command=unar; pkg_manager=pacman; package=unarchiver" ;;
        "unrar")
            _command_exists "bsdtar" && continue
            _command_exists "unar" && continue
            dependencies+="command=unrar"
            ;;
        "unsquashfs") dependencies+="command=unsquashfs; package=squashfs-tools" ;;
        "unzip")
            _command_exists "bsdtar" && continue
            _command_exists "unar" && continue
            _command_exists "7za" && continue
            dependencies+="command=unzip"
            ;;
        "unzip_new")
            _command_exists "unar" && continue
            _command_exists "7za" && continue
            dependencies+="command=bsdtar; pkg_manager=apt; package=libarchive-tools | command=bsdtar; pkg_manager=dnf | command=bsdtar; pkg_manager=pacman"
            ;;
        "unzip_new+password")
            show_wait_box=false
            _command_exists "7za" && continue
            dependencies+="command=bsdtar; pkg_manager=apt; package=libarchive-tools | command=bsdtar; pkg_manager=dnf | command=bsdtar; pkg_manager=pacman"
            ;;
        "xorriso")
            _command_exists "bsdtar" && continue
            _command_exists "unar" && continue
            dependencies+="command=xorriso"
            ;;
        "xz" | "lzma")
            _command_exists "bsdtar" && continue
            _command_exists "unar" && continue
            _command_exists "7za" && continue
            dependencies+="command=xz; pkg_manager=apt; package=xz-utils | command=xz; pkg_manager=dnf | command=xz; pkg_manager=pacman"
            ;;
        "zpaq") dependencies+="command=zpaq" ;;
        "zstd") dependencies+="command=zstd" ;;
        esac
        dependencies+=$'\n'
    done

    _check_dependencies "$dependencies"
    $show_wait_box && _display_wait_box

    export -f _get_command_use

    # Execute the function '_main_task' for each file in parallel.
    _run_task_parallel "$input_files" ""
    _display_result_box ""
}

_main_task() {
    local input_file=$1
    local output_dir=$2
    local std_output=""

    if [[ -z "$output_dir" ]]; then
        output_dir=$(dirname -- "$input_file")
    fi

    # Use a local temporary directory to work.
    local filename=""
    local temp_dir_output=""
    filename=$(basename -- "$input_file")             # Remove the path.
    filename=$(_strip_filename_extension "$filename") # Remove the extension.

    __use_temp_dir() {
        temp_dir_output=$(mktemp --directory --tmpdir="$output_dir" "tmp.$filename.XXXXXXXXXX")
        pushd "$temp_dir_output" &>/dev/null || true
    }

    __abort_extraction() {
        # Remove the temporary directory and abort the extraction.
        rm -rf -- "$temp_dir_output"
        exit 0
    }

    # Extract the archive according to the file extension.
    case $(_get_command_use "$input_file") in
    "_unknown_")
        __use_temp_dir
        local exit_code=0

        # Try to extract with 'unar'.
        std_output=$(unar -- "$input_file" 2>&1)
        exit_code=$?

        # Try to extract with '7za'.
        if ((exit_code != 0)); then
            std_output=$(7za x -aoa -- "$input_file" 2>&1)
            exit_code=$?
        fi

        if ((exit_code != 0)); then
            std_output="Could not recognize the archive format." && false
        fi
        ;;
    "7za")
        __use_temp_dir
        if _command_exists "7za"; then
            std_output=$(7za x -aoa -- "$input_file" 2>&1)
        elif _command_exists "bsdtar"; then
            std_output=$(bsdtar -xf "$input_file" 2>&1)
        elif _command_exists "unar"; then
            std_output=$(unar -- "$input_file" 2>&1)
        fi
        ;;
    "7za+password")
        local password=""
        password=$(_display_password_box_message "Password required for '$(basename -- "$input_file")'\n\nPassword:") || __abort_extraction
        __use_temp_dir
        std_output=$(7za x -aoa -p"$password" -- "$input_file" 2>&1)
        ;;
    "ar")
        __use_temp_dir
        std_output=$(ar x -- "$input_file" 2>&1)
        ;;
    "bzip2")
        __use_temp_dir
        if _command_exists "bzip2"; then
            std_output=$(bzip2 -d -c -k -- "$input_file" >"$filename" 2>&1)
        elif _command_exists "bsdtar"; then
            std_output=$(bsdtar -xf "$input_file" 2>&1)
        elif _command_exists "unar"; then
            std_output=$(unar -- "$input_file" 2>&1)
        elif _command_exists "7za"; then
            std_output=$(7za x -aoa -- "$input_file" 2>&1)
        fi
        ;;
    "cpio")
        __use_temp_dir
        if _command_exists "cpio"; then
            std_output=$(cpio -idv <"$input_file" 2>&1)
        elif _command_exists "bsdtar"; then
            std_output=$(bsdtar -xf "$input_file" 2>&1)
        elif _command_exists "unar"; then
            std_output=$(unar -- "$input_file" 2>&1)
        fi
        ;;
    "gpg")
        __use_temp_dir
        std_output=$(gpg --batch --yes --decrypt --output "$filename" -- "$input_file" 2>&1)
        ;;
    "gzip" | "compress")
        __use_temp_dir
        if _command_exists "gzip"; then
            std_output=$(gzip -d -c -k -- "$input_file" >"$filename" 2>&1)
        elif _command_exists "bsdtar"; then
            std_output=$(bsdtar -xf "$input_file" 2>&1)
        elif _command_exists "unar"; then
            std_output=$(unar -- "$input_file" 2>&1)
        elif _command_exists "7za"; then
            std_output=$(7za x -aoa -- "$input_file" 2>&1)
        fi
        ;;
    "lha")
        __use_temp_dir
        if _command_exists "lha"; then
            std_output=$(lha -e "$input_file" 2>&1)
        elif _command_exists "unar"; then
            std_output=$(unar -- "$input_file" 2>&1)
        fi
        ;;
    "lrzip")
        __use_temp_dir
        std_output=$(lrzip -d -o "$temp_dir_output/$filename" -- "$input_file" 2>&1)
        ;;
    "lz4")
        __use_temp_dir
        std_output=$(lz4 -d -c -- "$input_file" >"$filename" 2>&1)
        ;;
    "lzip")
        __use_temp_dir
        std_output=$(lzip -d -c -k -- "$input_file" >"$filename" 2>&1)
        ;;
    "lzma")
        __use_temp_dir
        std_output=$(xz -d -c -k --format=lzma -- "$input_file" >"$filename" 2>&1)
        ;;
    "lzop")
        __use_temp_dir
        std_output=$(lzop -d -- "$input_file" 2>&1)
        ;;
    "tar")
        __use_temp_dir
        if _command_exists "tar"; then
            std_output=$(tar --extract --file="$input_file" 2>&1)
        elif _command_exists "bsdtar"; then
            std_output=$(bsdtar -xf "$input_file" 2>&1)
        elif _command_exists "unar"; then
            std_output=$(unar -- "$input_file" 2>&1)
        elif _command_exists "7za"; then
            std_output=$(7za x -aoa -- "$input_file" 2>&1)
        fi
        ;;
    "tar+bzip2")
        __use_temp_dir
        if _command_exists "tar"; then
            std_output=$(tar --extract --bzip2 --file="$input_file" 2>&1)
        elif _command_exists "bsdtar"; then
            std_output=$(bsdtar -xf "$input_file" 2>&1)
        elif _command_exists "unar"; then
            std_output=$(unar -- "$input_file" 2>&1)
        elif _command_exists "7za"; then
            std_output=$(7za x -aoa -- "$input_file" 2>&1)
        fi
        ;;
    "tar+compress")
        __use_temp_dir
        if _command_exists "tar"; then
            std_output=$(tar --extract --file="$input_file" 2>&1)
        elif _command_exists "bsdtar"; then
            std_output=$(bsdtar -xf "$input_file" 2>&1)
        elif _command_exists "unar"; then
            std_output=$(unar -- "$input_file" 2>&1)
        elif _command_exists "7za"; then
            std_output=$(7za x -aoa -- "$input_file" 2>&1)
        fi
        ;;
    "tar+gzip")
        __use_temp_dir
        if _command_exists "tar"; then
            std_output=$(tar --extract --gzip --file="$input_file" 2>&1)
        elif _command_exists "bsdtar"; then
            std_output=$(bsdtar -xf "$input_file" 2>&1)
        elif _command_exists "unar"; then
            std_output=$(unar -- "$input_file" 2>&1)
        elif _command_exists "7za"; then
            std_output=$(7za x -aoa -- "$input_file" 2>&1)
        fi
        ;;
    "tar+lrzip")
        __use_temp_dir
        std_output=$(lrztar -d "$input_file" 2>&1)
        ;;
    "tar+lz4")
        __use_temp_dir
        std_output=$(lz4 -d -c -- "$input_file" | tar xf - 2>&1)
        ;;
    "tar+lzip")
        __use_temp_dir
        std_output=$(tar --extract --lzip --file="$input_file" 2>&1)
        ;;
    "tar+lzma")
        __use_temp_dir
        if _command_exists "tar"; then
            std_output=$(tar --extract --lzma --file="$input_file" 2>&1)
        elif _command_exists "bsdtar"; then
            std_output=$(bsdtar -xf "$input_file" 2>&1)
        elif _command_exists "unar"; then
            std_output=$(unar -- "$input_file" 2>&1)
        elif _command_exists "7za"; then
            std_output=$(7za x -aoa -- "$input_file" 2>&1)
        fi
        ;;
    "tar+lzop")
        __use_temp_dir
        std_output=$(tar --extract --lzop --file="$input_file" 2>&1)
        ;;
    "tar+xz")
        __use_temp_dir
        if _command_exists "tar"; then
            std_output=$(tar --extract --xz --file="$input_file" 2>&1)
        elif _command_exists "bsdtar"; then
            std_output=$(bsdtar -xf "$input_file" 2>&1)
        elif _command_exists "unar"; then
            std_output=$(unar -- "$input_file" 2>&1)
        elif _command_exists "7za"; then
            std_output=$(7za x -aoa -- "$input_file" 2>&1)
        fi
        ;;
    "tar+zstd")
        __use_temp_dir
        std_output=$(zstd -d -c -- "$input_file" | tar xf - 2>&1)
        ;;
    "unar")
        __use_temp_dir
        std_output=$(unar -- "$input_file" 2>&1)
        ;;
    "unrar")
        __use_temp_dir
        if _command_exists "unrar"; then
            std_output=$(unrar x -- "$input_file" 2>&1)
        elif _command_exists "bsdtar"; then
            std_output=$(bsdtar -xf "$input_file" 2>&1)
        elif _command_exists "unar"; then
            std_output=$(unar -- "$input_file" 2>&1)
        fi
        ;;
    "unsquashfs")
        __use_temp_dir
        std_output=$(unsquashfs "$input_file" 2>&1)
        ;;
    "unzip")
        __use_temp_dir
        if _command_exists "7za"; then
            std_output=$(7za x -aoa -- "$input_file" 2>&1)
        elif _command_exists "bsdtar"; then
            std_output=$(bsdtar -xf "$input_file" 2>&1)
        elif _command_exists "unar"; then
            std_output=$(unar -- "$input_file" 2>&1)
        elif _command_exists "unzip"; then
            std_output=$(unzip -- "$input_file" 2>&1)
        fi
        ;;
    "unzip_new")
        __use_temp_dir
        if _command_exists "7za"; then
            std_output=$(7za x -aoa -- "$input_file" 2>&1)
        elif _command_exists "bsdtar"; then
            std_output=$(bsdtar -xf "$input_file" 2>&1)
        elif _command_exists "unar"; then
            std_output=$(unar -- "$input_file" 2>&1)
        fi
        ;;
    "unzip_new+password")
        local password=""
        password=$(_display_password_box_message "Password required for '$(basename -- "$input_file")'\n\nPassword:") || __abort_extraction
        __use_temp_dir
        if _command_exists "7za"; then
            std_output=$(7za x -aoa -p"$password" -- "$input_file" 2>&1)
        elif _command_exists "bsdtar"; then
            std_output=$(bsdtar --passphrase "$password" -xf "$input_file" 2>&1)
        fi
        ;;
    "xorriso")
        __use_temp_dir
        if _command_exists "xorriso"; then
            std_output=$(xorriso -osirrox on -indev "$input_file" -find / -exec chmod u+rw -- -extract / . -rollback_end 2>&1)
        elif _command_exists "bsdtar"; then
            std_output=$(bsdtar -xf "$input_file" 2>&1)
            chmod -R u+rw . &>/dev/null
        elif _command_exists "unar"; then
            std_output=$(unar -- "$input_file" 2>&1)
        fi
        ;;
    "xz")
        __use_temp_dir
        if _command_exists "xz"; then
            std_output=$(xz -d -c -k -- "$input_file" >"$filename" 2>&1)
        elif _command_exists "bsdtar"; then
            std_output=$(bsdtar -xf "$input_file" 2>&1)
        elif _command_exists "unar"; then
            std_output=$(unar -- "$input_file" 2>&1)
        elif _command_exists "7za"; then
            std_output=$(7za x -aoa -- "$input_file" 2>&1)
        fi
        ;;
    "zpaq")
        __use_temp_dir
        std_output=$(zpaq x "$input_file" 2>&1)
        ;;
    "zstd")
        __use_temp_dir
        std_output=$(zstd -d -c -- "$input_file" >"$filename" 2>&1)
        ;;
    esac

    # Check for result errors.
    _check_output "$?" "$std_output" "$input_file" "" || __abort_extraction

    # Check if the archive has just one item (single file/directory compressed).
    local count_root_items=""
    local single_output_item=""
    count_root_items=$(find . -mindepth 1 -maxdepth 1 2>/dev/null | wc -l)
    if ((count_root_items == 1)); then
        single_output_item=$(find . -mindepth 1 -maxdepth 1 2>/dev/null)
        single_output_item="${single_output_item#./}"
    fi

    popd &>/dev/null || true

    # Check if the 'temp_dir_output' is empty.
    if ((count_root_items == 0)); then
        __abort_extraction
    fi

    # Move the items to the correct directory.
    if [[ "$filename" == "$single_output_item" ]] ||
        [[ "$filename" == "$(_strip_filename_extension "$single_output_item")" ]]; then
        # For archives with "one item with the same name of the archive".
        # For example: "README.TXT.tar.gz" or "README.tar.gz".
        std_output=$(_move_file "rename" "$temp_dir_output/$single_output_item" "$output_dir/$single_output_item" 2>&1)
        _check_output "$?" "$std_output" "$input_file" ""
    elif [[ "squashfs-root" == "$single_output_item" ]]; then
        # For SquashFS.
        std_output=$(_move_file "rename" "$temp_dir_output/$single_output_item" "$output_dir/$filename" 2>&1)
        _check_output "$?" "$std_output" "$input_file" ""
    elif ((count_root_items > 0)); then
        # For archives with "one item with a different name of the archive" or "multiple items".
        std_output=$(_move_file "rename" "$temp_dir_output" "$output_dir/$filename" 2>&1)
        _check_output "$?" "$std_output" "$input_file" ""
    fi

    __abort_extraction
}

_get_command_use() {
    local input_file=$1
    local command_use=""
    local file_mime=""
    local filename_extension=""

    # Get the mime type and filename extension to define what command to use.
    file_mime=$(_get_file_mime "$input_file")
    filename_extension=$(_get_filename_extension "$input_file")

    # NOTE: See the file: /usr/share/mime/packages/freedesktop.org.xml
    case "${file_mime,,}" in
    "application/x-7z-compressed") command_use="7za" ;;          # 7z
    "application/x-ace") command_use="unar" ;;                   # ace
    "application/x-alz") command_use="unar" ;;                   # alz
    "application/x-arc") command_use="unar" ;;                   # arc
    "application/x-arj") command_use="unar" ;;                   # arj
    "application/bzip2") command_use="bzip2" ;;                  # bz, bz2
    "application/x-bzip") command_use="bzip2" ;;                 # bz, bz2
    "application/x-bzip2") command_use="bzip2" ;;                # bz, bz2
    "application/vnd.ms-cab-compressed") command_use="unar" ;;   # cab
    "application/x-cpio") command_use="cpio" ;;                  # cpio
    "application/vnd.debian.binary-package") command_use="ar" ;; # deb
    "application/gzip") command_use="gzip" ;;                    # gz
    "application/x-gzip") command_use="gzip" ;;                  # gz
    "application/pgp-encrypted") command_use="gpg" ;;            # gpg
    "application/x-iso9660-image") command_use="xorriso" ;;      # iso
    "application/x-lrzip") command_use="lrzip" ;;                # lrz
    "application/x-lzip") command_use="lzip" ;;                  # lz
    "application/x-lz4") command_use="lz4" ;;                    # lz4
    "application/x-lha") command_use="lha" ;;                    # lzh
    "application/x-lzh-compressed") command_use="lha" ;;         # lzh
    "application/x-lzma") command_use="lzma" ;;                  # lzma
    "application/x-lzop") command_use="lzop" ;;                  # lzo
    "application/x-msi") command_use="unar" ;;                   # msi
    "application/x-pak") command_use="unar" ;;                   # pak
    "application/vnd.rar") command_use="unrar" ;;                # rar
    "application/x-rar-compressed") command_use="unrar" ;;       # rar
    "application/x-rar") command_use="unrar" ;;                  # rar
    "application/x-stuffit") command_use="unar" ;;               # sit
    "application/stuffit") command_use="unar" ;;                 # sit
    "application/x-sit") command_use="unar" ;;                   # sit
    "application/vnd.squashfs") command_use="unsquashfs" ;;      # sqsh
    "application/x-xar") command_use="unar" ;;                   # xar
    "application/x-xz") command_use="xz" ;;                      # xz
    "application/x-compress") command_use="compress" ;;          # z
    "application/x-zip-compressed") command_use="unzip" ;;       # zip
    "application/x-zip") command_use="unzip" ;;                  # zip
    "application/zip") command_use="unzip" ;;                    # zip
    "application/x-zoo") command_use="unar" ;;                   # zoo
    "application/zstd") command_use="zstd" ;;                    # zst
    #"application/x-gtar") command_use="tar" ;;                   # tar (conflict with 'cpio' files)
    #"application/x-tar") command_use="tar" ;;                    # tar (conflict with 'cpio' files)
    *)
        # If not found the 'file_mime', use the extension.
        case "${filename_extension,,}" in
        *.tar.bz | *.tbz | *.tar.bz2 | *.tbz2 | *.tb2) command_use="tar+bzip2" ;;
        *.tar.gz | *.tgz) command_use="tar+gzip" ;;
        *.tar.lrz | *.tlrz) command_use="tar+lrzip" ;;
        *.tar.lz) command_use="tar+lzip" ;;
        *.tar.lz4) command_use="tar+lz4" ;;
        *.tar.lzma | *.tlz) command_use="tar+lzma" ;;
        *.tar.lzo | *.tzo) command_use="tar+lzop" ;;
        *.tar.xz | *.txz) command_use="tar+xz" ;;
        *.tar.z | *.taz) command_use="tar+compress" ;;
        *.tar.zst | *.tzst) command_use="tar+zstd" ;;
        *.7z) command_use="7za" ;;
        *.ace) command_use="unar" ;;
        *.alz) command_use="unar" ;;
        *.arc) command_use="unar" ;;
        *.arj) command_use="unar" ;;
        *.bz | *.bz2) command_use="bzip2" ;;
        *.cab) command_use="unar" ;;
        *.cpio) command_use="cpio" ;;
        *.deb | *.udeb) command_use="ar" ;;
        *.gpg | *.asc | *.pgp) command_use="gpg" ;;
        *.gz) command_use="gzip" ;;
        *.iso | *.iso9660) command_use="xorriso" ;;
        *.lrz) command_use="lrzip" ;;
        *.lz) command_use="lzip" ;;
        *.lz4) command_use="lz4" ;;
        *.lzh | *.lzs | *.lha) command_use="lha" ;;
        *.lzma) command_use="lzma" ;;
        *.lzo) command_use="lzop" ;;
        *.msi) command_use="unar" ;;
        *.pak) command_use="unar" ;;
        *.rar) command_use="unrar" ;;
        *.sit) command_use="unar" ;;
        *.sqsh | *.squashfs | *.sfs) command_use="unsquashfs" ;;
        *.tar | *.gtar | *.gem) command_use="tar" ;;
        *.xar) command_use="unar" ;;
        *.xz) command_use="xz" ;;
        *.z) command_use="compress" ;;
        *.zip) command_use="unzip" ;;
        *.zoo) command_use="unar" ;;
        *.zpaq) command_use="zpaq" ;;
        *.zst) command_use="zstd" ;;
        *) command_use="_unknown_" ;;
        esac
        ;;
    esac

    # Check if the file is a 'tar' compressed (using the filename).
    if [[ "${filename_extension,,}" = *".tar."* ]]; then
        case "$command_use" in
        "bzip2" | "compress" | "gzip" | "lrzip" | "lz4" | "lzip" | "lzma" | "lzop" | "xz" | "zstd")
            command_use="tar+$command_use"
            ;;
        esac
    fi

    # Check if if the 'zip' archive is password-protected.
    if [[ "$command_use" == "unzip" ]]; then
        if _command_exists "zipinfo"; then
            if zipinfo -v "$input_file" 2>&1 | tr -d " " | grep -i -q "status:encrypted"; then
                command_use="unzip_new+password"
                _command_exists "7za" && command_use="7za+password"
            fi
        elif _command_exists "7za"; then
            if 7za t -slt -p"null" -- "$input_file" 2>&1 | grep -i -q "wrong password"; then
                command_use="unzip_new+password"
            fi
        fi
    fi

    # Check if if the '7z' archive is password-protected.
    if [[ "$command_use" == "7za" ]]; then
        if _command_exists "7za"; then
            if 7za t -slt -p"null" -- "$input_file" 2>&1 | grep -i -q "wrong password"; then
                command_use="7za+password"
            fi
        elif _command_exists "bsdtar"; then
            if bsdtar -tf "$input_file" 2>&1 | grep -i -q "encrypted"; then
                command_use="7za+password"
            fi
        elif _command_exists "lsar"; then
            if lsar -- "$input_file" 2>&1 | grep -i -q "requires a password"; then
                command_use="7za+password"
            fi
        fi
    fi

    # Check if the zip require new unzip version to extract.
    if [[ "$command_use" == "unzip" ]]; then
        if file --dereference --brief -- "$input_file" 2>/dev/null | grep -i -q "at least v[4-9]"; then
            command_use="unzip_new"
        fi
    fi

    printf "%s" "$command_use"
}

_main "$@"
