#!/usr/bin/env bash

# Source the file 'scripts/common-functions'
# shellcheck disable=SC1090
source "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")" | sed 's|\(scripts\).*|\1/common-functions|')"

# Initial checks
_check_dependencies convert || exit 1
INPUT_FILES=$(_get_files "$*" "image" "1" "" "") || exit 1
OUTPUT_DIR=$(_get_output_dir) || exit 1

for FILE in $INPUT_FILES; do
    # Run the process (part 1)
    OUTPUT_FILE="$(_get_filename_without_extension "$FILE")-2parts-v.pdf"
    STD_OUTPUT_1="$(convert -crop 50%x100% +repage "$FILE" "$OUTPUT_DIR/.tmp.jpg" 2>&1)"
    EXIT_CODE_1=$?

    _log_result_error "$FILE" "$STD_OUTPUT_1" "$OUTPUT_DIR" "$EXIT_CODE_1" "$OUTPUT_FILE"

    # Run the process (part 2)
    STD_OUTPUT_2="$(convert "$OUTPUT_DIR"/.tmp-0.jpg "$OUTPUT_DIR"/.tmp-1.jpg "$OUTPUT_DIR/$OUTPUT_FILE" 2>&1)"
    EXIT_CODE_2=$?

    _log_result_error "$FILE" "$STD_OUTPUT_2" "$OUTPUT_DIR" "$EXIT_CODE_2" "$OUTPUT_FILE"

    rm -rf "$OUTPUT_DIR"/.tmp*.jpg
done

_display_result "$OUTPUT_DIR"
