#!/usr/bin/env bash
# shellcheck disable=SC2001

# Source the script 'common-functions.sh'.
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/common-functions.sh"

_main() {
    local input_files=""
    local std_output=""

    # Execute initial checks.
    _check_dependencies ""
    _display_wait_box
    input_files=$(_get_files "type:file, recursive:true, get_pwd_if_no_selection:true, skip_encoding:binary, skip_extension:pdf|svg")

    # Run the main process.
    # shellcheck disable=SC2086
    std_output=$(file --dereference --separator "//" --no-pad -- $input_files)
    std_output=$(_text_remove_pwd "$std_output")
    std_output=$(sed "s|//.*with CRLF, CR, LF line.*|// CRLF+CR+LF (windows)|" <<<"$std_output")
    std_output=$(sed "s|//.*with CRLF, LF line.*|// CRLF+LF (windows)|" <<<"$std_output")
    std_output=$(sed "s|//.*with CRLF, CR line.*|// CRLF+CR (windows)|" <<<"$std_output")
    std_output=$(sed "s|//.*with CRLF line.*|// CRLF (windows)|" <<<"$std_output")
    std_output=$(sed "s|//.*with CR line.*|// CR (mac)|" <<<"$std_output")
    std_output=$(sed "s|//.*with CR, LF line.*|// CR+LF (mac)|" <<<"$std_output")
    std_output=$(sed "s|//.*no line.*|// (no line)|" <<<"$std_output")
    std_output=$(sed "s|//.*text.*|// LF (unix)|" <<<"$std_output")
    std_output=$(sed "s|\(.*\)// *\(.*\)|\2: '\1'|" <<<"$std_output")
    std_output=$(grep "(windows):\|(unix):\|(mac):\|(no line):" <<<"$std_output")
    std_output=$(_text_sort "$std_output")

    _display_text_box "$std_output"
}

_main "$@"
