#!/usr/bin/env bash

# Import the script 'common-functions.sh'
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/common-functions.sh"

_main() {
    local input_files=""
    local output_dir=""

    # Initial checks
    _check_dependencies "unexpand(coreutils)"
    _display_wait_box
    input_files=$(_get_files "$*" "type=file; mime=text,application; skip_encoding=binary; skip_extension=pdf")
    output_dir=$(_get_output_dir)

    _run_main_task_parallel "$input_files" "$output_dir"
    _display_result_box "$output_dir"
}

_main_task() {
    local input_file=$1
    local output_dir=$2
    local output_file=""
    local std_output=""
    local temp_file=""

    # Work on a temporary file
    temp_file=$(mktemp --tmpdir="$TEMP_DIR_TASK")

    # Run the main process
    std_output=$(unexpand --tabs=4 -- "$input_file" >"$temp_file")
    _check_result "$?" "$std_output" "$input_file" "$output_file" || return 1

    # Move the temporary file to the output
    output_file=$(_get_output_file "$input_file" "$output_dir" "")
    _move_temp_file_to_output "$input_file" "$temp_file" "$output_file" || return 1

    # Remove the temporary files on each iteration (if not removed before)
    rm -rf "$temp_file"
}

_main "$@"
