#!/usr/bin/env bash

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
# shellcheck source=/dev/null
source "${SCRIPT_DIR%/*}/common-functions"

# Initial checks
_check_dependencies meld || exit 1
INPUT_FILES=$(_get_files "$*" "directory" "2" "3" "d") || exit 1

# Run the main process
# shellcheck disable=SC2086
meld $INPUT_FILES &
