#!/usr/bin/env bash

# Source the file 'scripts/common-functions'
# shellcheck disable=SC1090
source "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")" | sed 's|\(scripts\).*|\1/common-functions|')"

# Initial checks
INPUT_FILES=$(_get_files "$*" "directory" "1" "" "d") || exit 1
OUTPUT_DIR="$PWD"

_flatten() {
    DIRECTORY="$1"
    (
        cd "$DIRECTORY" || true
        UNDO_SCRIPT="undo.sh"
        TEMP_LIST_FILES=$(mktemp)

        # Make a list of files to move
        find . -type f >"$TEMP_LIST_FILES"

        # Make 'undo' file
        echo "#!/usr/bin/env bash" >"$UNDO_SCRIPT"

        # Make a backup of directory tree
        find . -type d | grep "/" | xargs -I{} echo "mkdir -p \"{}\"" >>"$UNDO_SCRIPT"

        while read -r FULL_PATH_FILENAME; do
            FILENAME=$(basename "$FULL_PATH_FILENAME")

            # Print 'mv' command in Undo script
            echo "mv \"$FILENAME\" \"$FULL_PATH_FILENAME\"" >>"$UNDO_SCRIPT"

            # Move all selected files to local folder
            _move_file "$FULL_PATH_FILENAME" "$FILENAME"
        done <"$TEMP_LIST_FILES"

        # Command to delete 'undo' file after the process
        echo "rm -f \"$UNDO_SCRIPT\"" >>"$UNDO_SCRIPT"

        # Set the 'undo' file as executable
        chmod +x "$UNDO_SCRIPT"

        # Remove empty directories
        find . -type d -empty -delete

        # Remove temporary file
        rm -f "$TEMP_LIST_FILES"
    )
}

for DIRECTORY in $INPUT_FILES; do
    # Run the main process
    _flatten "$DIRECTORY"
done

# TODO: Implement the use of the function '_check_successful_finish'

_display_result "$OUTPUT_DIR"
