#!/usr/bin/env bash

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
# shellcheck source=/dev/null
source "${SCRIPT_DIR%/*}/common-functions"

# Initial checks
INPUT_FILES=$(_get_files "$*" "directory" "1" "" "d") || exit 1

# Run the main process
# shellcheck disable=SC2086
STD_OUTPUT=$(du -h $INPUT_FILES)
STD_OUTPUT=$(echo "$STD_OUTPUT" | sort -h -r)
STD_OUTPUT=$(echo "$STD_OUTPUT" | head -n 10)
STD_OUTPUT=$(echo "$STD_OUTPUT" | sed -r "s|\t(.*)|\t\"\1\"|")

_display_info_box "$STD_OUTPUT" "Top largest directories"
