#!/usr/bin/env bash

# Source the file 'scripts/common-functions'
# shellcheck disable=SC1090
source "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")" | sed 's|\(scripts\).*|\1/common-functions|')"

# Initial checks
INPUT_FILES=$(_get_files "$*" "directory" "1" "" "d") || exit 1
OUTPUT_DIR="$PWD"

for DIRECTORY in $INPUT_FILES; do
    # Run the main process
    STD_OUTPUT="$(find "$DIRECTORY" -type d -empty -delete)"
    EXIT_CODE=$?

    _log_result_error "$FILE" "$STD_OUTPUT" "$OUTPUT_DIR" "$EXIT_CODE" ""
done

_display_result "$OUTPUT_DIR"
