#!/usr/bin/env bash

# Source the script '.common-functions.sh'.
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/.common-functions.sh"

_main() {
    local input_files=""
    local output_dir=""

    # Execute initial checks.
    _check_dependencies "mediainfo"
    _display_wait_box
    input_files=$(_get_files "par_type=file; par_recursive=true; par_select_mime='audio/|video/'")

    # Execute the function '_main_task' for each file in parallel.
    _run_task_parallel "$input_files" "$output_dir"

    local std_output=""
    std_output=$(_storage_text_read_all)
    std_output=$(_text_sort "$std_output")

    _display_list_box "$std_output" "par_item_name=$(_i18n 'files'); par_columns='--column:$(_i18n 'Duration'),--column:$(_i18n 'Album'),--column:$(_i18n 'Artist'),--column:$(_i18n 'Title'),--column:$(_i18n 'File')'; par_action=open_location; par_check_type=checkbox"
}

_main_task() {
    local input_file=$1
    local output_dir=$2
    local std_output=""

    # Run the main process.
    std_output=$(LC_ALL=C mediainfo --Inform="General;Duration:%Duration/String3%\nAlbum:%Album%\nTitle:%Title%\nPerformer:%Performer%" -- "$input_file" 2>&1)
    _check_output "$?" "$std_output" "$input_file" "" || return 1

    local tag_duration=""
    local tag_album=""
    local tag_artist=""
    local tag_title=""
    tag_duration=$(grep -m1 "^Duration:" <<<"$std_output" | cut -d ":" -f 2- | sed "s|\.[0-9][0-9]*$||")
    tag_album=$(grep -m1 "^Album:" <<<"$std_output" | cut -d ":" -f 2-)
    tag_artist=$(grep -m1 "^Performer:" <<<"$std_output" | cut -d ":" -f 2-)
    tag_title=$(grep -m1 "^Title:" <<<"$std_output" | cut -d ":" -f 2-)

    _storage_text_write_ln "$tag_duration$FIELD_SEPARATOR$tag_album$FIELD_SEPARATOR$tag_artist$FIELD_SEPARATOR$tag_title$FIELD_SEPARATOR$(_text_remove_pwd "$input_file")"
}

_main "$@"
