#!/usr/bin/env bash

# Source the script '_common-functions.sh'.
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/_common-functions.sh"

_main() {
    local input_files=""
    local content_files=""

    # Execute initial checks.
    _dependencies_check_commands_clipboard ""
    _display_wait_box "2"
    input_files=$(_get_files "par_type=file; par_skip_encoding='binary'")

    # shellcheck disable=SC2086
    content_files=$(cat -- $input_files 2>/dev/null)

    # Run the main process.
    _set_clipboard_data "$content_files"

    _display_result_box ""
}

_main "$@"
