#!/usr/bin/env bash

# Source the script '_common-functions.sh'.
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/_common-functions.sh"

_main() {
    local output_dir=""

    # Execute initial checks.
    _check_dependencies_clipboard ""
    _display_wait_box "2"
    input_files=$(_get_files "par_type=all; par_recursive=true")

    # shellcheck disable=SC2086
    input_files=$(basename --multiple -- $input_files)

    # Run the main process.
    _set_clipboard_data "$input_files"

    _display_result_box ""
}

_main "$@"
