#!/usr/bin/env bash

# Source the script '_common-functions.sh'.
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/_common-functions.sh"

_main() {
    local output_dir=""

    # Execute initial checks.
    _dependencies_check_commands_clipboard ""
    _display_wait_box "2"
    output_dir=$(_get_output_dir "par_use_same_dir=true")

    # Run the main process.
    _save_file_from_clipboard "$output_dir"

    _display_result_box "$output_dir"
}

_save_file_from_clipboard() {
    local output_dir=$1
    local file_type=""
    local output_file=""
    local std_output=""

    if [[ "${XDG_SESSION_TYPE:-}" == "wayland" ]]; then

        file_type=$(wl-paste --list-types 2>/dev/null)

        case "$file_type" in
        *"image/png"*)
            output_file=$(_get_output_filename "Clipboard.png" \
                "$output_dir" "par_extension_opt=preserve")

            wl-paste --no-newline --type "image/png" \
                >"$output_file" 2>/dev/null
            ;;
        *"text/html"*)
            output_file=$(_get_output_filename "Clipboard.html" \
                "$output_dir" "par_extension_opt=preserve")

            wl-paste --no-newline --type "text/html" \
                >"$output_file" 2>/dev/null
            ;;
        *"text/plain"*)
            output_file=$(_get_output_filename "Clipboard.txt" \
                "$output_dir" "par_extension_opt=preserve")

            wl-paste --no-newline --type "text/plain" \
                >"$output_file" 2>/dev/null
            ;;
        esac

    else

        file_type=$(xclip -selection clipboard -t TARGETS -o 2>/dev/null)

        case "$file_type" in
        *"image/png"*)
            output_file=$(_get_output_filename "Clipboard.png" \
                "$output_dir" "par_extension_opt=preserve")

            xclip -selection clipboard -t "image/png" -o \
                >"$output_file" 2>/dev/null
            ;;
        *"text/html"*)
            output_file=$(_get_output_filename "Clipboard.html" \
                "$output_dir" "par_extension_opt=preserve")

            xclip -selection clipboard -t "text/html" -o \
                >"$output_file" 2>/dev/null
            ;;
        *"text/plain"*)
            output_file=$(_get_output_filename "Clipboard.txt" \
                "$output_dir" "par_extension_opt=preserve")

            xclip -selection clipboard -t "text/plain" -o \
                >"$output_file" 2>/dev/null
            ;;
        esac

    fi

    _check_output "$?" "$std_output" "" "$output_file" || return 1
}

_main "$@"
