#!/usr/bin/env bash

# Source the script '.common-functions.sh'.
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/.common-functions.sh"

_main() {
    local input_files=""
    local output_dir=""

    # Execute initial checks.
    _check_dependencies ""
    _display_wait_box
    input_files=$(_get_files "par_type=file; par_recursive=true; par_skip_encoding='binary'; par_skip_extension='pdf|svg'")

    # Execute the function '_main_task' for each file in parallel.
    _run_task_parallel "$input_files" "$output_dir"

    local std_output=""
    std_output=$(_storage_text_read_all)
    std_output=$(_text_sort "$std_output")

    _display_list_box "$std_output" "par_columns='--column:Char,--column:Line,--column:File'; par_item_name='files with bad chars'; par_action=open_location; par_checkbox=true"
}

_main_task() {
    local input_file=$1
    local output_dir=$2
    local std_output=""

    # Run the main process.
    std_output=$(
        grep --ignore-case --perl-regexp --only-matching --line-number \
            "[^ \w\t\n\r\-\,\;\:\!\?\.\'\"\(\)\[\]\{\}\@\*\/\\\&\#\%\`\^\+\<\=\>\|\~\$áàâãçéêíóôõú\“\”–—…«»§•°©®←→↑↓↔↕↖↗↘↙⇐⇑⇒⇓⇔⇕⇠⇡⇢⇣◄►▲▼◂▸◃▹◀▶◁▷△▽⯇⯈⯅⯆⬅➡⬆⬇⬈⬊⬉⬋⮘⮚⮙⮛∀∃∆∇∈∉∏∑±÷≠¬∘√∛∜∝∞∠∥∧∩∫∬∭∮∴∵≈≤≥⊂⊃⊆⊇⊥▪▫▸►○●◦♦⟵⟶⟷€¹²³ªº™ΔµΣΩ¤ß]" \
            -- "$input_file" /dev/null
    )

    # Ignore emojis.
    std_output=$(grep -v --perl-regexp "[\x{2600}-\x{1F9FF}]" <<<"$std_output")

    std_output=$(_text_remove_pwd "$std_output")
    # shellcheck disable=SC2001
    std_output=$(sed "s|^\([^:]*\):\([^:]*\):\([^:]*\)$|\"\3\"$FIELD_SEPARATOR\2$FIELD_SEPARATOR\1|g" <<<"$std_output")

    _storage_text_write_ln "$std_output"
}

_main "$@"
