#!/usr/bin/env bash

# Import the script 'common-functions.sh'
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(echo "$SCRIPT_DIR" | grep --only-matching "^.*scripts[^/]*")
source "$ROOT_DIR/common-functions.sh"

# Initial checks
_check_dependencies "lpr(cups-bsd)"
_display_wait_box
INPUT_FILES=$(_get_files "$*" "type=file")
OUTPUT_DIR=$PWD

_main_task() {
    local INPUT_FILE=$1
    local OUTPUT_DIR=$2
    local STD_OUTPUT=""

    # Run the main process
    STD_OUTPUT=$(lpr "$INPUT_FILE" 2>&1)
    _check_result "$?" "$STD_OUTPUT" "$INPUT_FILE" "" || return 1
}

_run_main_task_parallel "$INPUT_FILES" "$OUTPUT_DIR"
_display_result_box "$OUTPUT_DIR"
