#!/usr/bin/env bash

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
# shellcheck source=/dev/null
source "${SCRIPT_DIR/%scripts\/*/scripts}/_common_functions"

# Initial checks
_check_dependencies findimagedupes eog || exit 1
INPUT_FILES=$(_get_files "$*" "a" "1" "" "") || exit 1

# Run the main process
# shellcheck disable=SC2086
findimagedupes --recurse --threshold=95% --program=/usr/bin/eog -- $INPUT_FILES 2>/dev/null
_display_result_tasks ""
