#!/usr/bin/env bash

# Source the file 'scripts/common-functions'
# shellcheck disable=SC1090
source "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")" | sed 's|\(scripts\).*|\1/common-functions|')"

# Initial checks
_check_dependency file zenity sed
INPUT_FILES=$(_check_files "$*" "text" "1" "" "r") || exit 1

# Run the main process
# shellcheck disable=SC2086
STD_OUTPUT=$(file --mime-encoding $INPUT_FILES | sed "s|\([^:]*\):[ ]*\([^ ]*\)|\2: '\1'|" | grep -v "binary:" | sort)
WIDTH_TEXT=$(echo "$STD_OUTPUT" | wc -L)
WIDTH_WINDOW=$((WIDTH_TEXT * 10))
echo "$STD_OUTPUT" | zenity --text-info --no-wrap --font="Liberation Mono" --height=300 --width="$WIDTH_WINDOW" --title "File informations (encoding)"
