#!/usr/bin/env bash

# Source the file 'scripts/common-functions'
# shellcheck disable=SC1090
source "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")" | sed 's|\(scripts\).*|\1/common-functions|')"

# Initial checks
INPUT_FILES=$(_check_files "$*" "" "1" "" "d") || exit 1
OUTPUT_DIR="$PWD"

for FILE in $INPUT_FILES; do
    OUTPUT_FILE=$(echo "$FILE" | tr "[:upper:]" "[:lower:]")
    TEMP_FILE="$FILE.tmp"

    if [ -f "$OUTPUT_FILE" ] | [ -f "$TEMP_FILE" ]; then
        _log_error "$FILE" "It was not possible to rename the file." "$OUTPUT_DIR"
        continue
    fi

    # Run the main process
    mv "$FILE" "$TEMP_FILE" && mv "$TEMP_FILE" "$OUTPUT_FILE"
done

_display_result ""
