#!/usr/bin/env bash

# Source the script 'common-functions.sh'.
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/common-functions.sh"

_main() {
    local input_files=""
    local output_dir=""

    # Execute initial checks.
    _check_dependencies "gpg(apt:gpg,pacman:gnupg,dnf:gnupg2)"
    _display_wait_box
    input_files=$(_get_files "type:file, extension:asc|gpg|pgp|sig")

    # Execute the function '_main_task' for each file in parallel.
    _run_task_parallel "$input_files" ""

    std_output=$(_process_result_compile)

    _display_text_box "$std_output"
}

_main_task() {
    local input_file=$1
    local output_dir=$2
    local std_output=""

    # Run the main process.
    std_output=$(gpg --yes --verify -- "$input_file" 2>&1)

    _process_result_write "\"$(_text_remove_pwd "$input_file")\""$'\n'"$std_output"$'\n'
}

_main "$@"
