#!/usr/bin/env bash

# Source the script 'common-functions.sh'.
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/common-functions.sh"

_main() {
    local input_files=""
    local output_dir=""

    # Execute initial checks.
    _check_dependencies "gpg(apt:gpg,pacman:gnupg,dnf:gnupg2) zenity"
    input_files=$(_get_files "type:file")
    output_dir=$(_get_output_dir "use_same_dir:true")

    local users=""
    users=$(gpg --list-secret-keys --with-colons | grep "^uid" | cut -d ':' -f 10)
    if [[ -z "$users" ]]; then
        _display_error_box "Signing failed: no secret keys installed!"
        _exit_script
    fi
    TEMP_DATA_TASK=$(echo "$users" | tr ':' '\n' | zenity --list --title="Select a user" --text="Select a user from the list below." --column="User" --height=200 --width=600 2>/dev/null) || _exit_script
    if [[ -z "$TEMP_DATA_TASK" ]]; then
        _display_error_box "Signing failed: you must select a user!"
        _exit_script
    fi

    _display_wait_box

    # Execute the function '_main_task' for each file in parallel.
    _run_task_parallel "$input_files" "$output_dir"
    _display_result_box "$output_dir"
}

_main_task() {
    local input_file=$1
    local output_dir=$2
    local output_file=""
    local std_output=""

    # Run the main process.
    output_file=$(_get_output_filename "$input_file" "$output_dir" "extension_opt:append, extension:sig")
    std_output=$(gpg --batch --yes --detach-sign --local-user "$TEMP_DATA_TASK" --output "$output_file" -- "$input_file" 2>&1)
    _check_output "$?" "$std_output" "$input_file" "$output_file" || return 1
}

_main "$@"
