#!/usr/bin/env bash

# Source the script '.common-functions.sh'.
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/.common-functions.sh"

_main() {
    local input_files=""
    local output_dir=""

    # Execute initial checks.
    _command_exists "magick" || _check_dependencies "convert"
    _display_wait_box
    input_files=$(_get_files "par_type=file; par_select_mime=image/")
    output_dir=$(_get_output_dir "par_use_same_dir=true")

    # Execute the function '_main_task' for each file in parallel.
    _run_task_parallel "$input_files" "$output_dir"
    _display_result_box "$output_dir"
}

_main_task() {
    local input_file=$1
    local output_dir=$2
    local output_file=""
    local std_output=""

    # Run the main process.
    local first_pixel_color=""
    first_pixel_color=$(_cmd_magick_convert "$input_file""[1x1+0+0]" -format "%[pixel:p{0,0}]" "info:" 2>&1)
    _check_output "$?" "$first_pixel_color" "$input_file" "" || return 1

    output_file=$(_get_output_filename "$input_file" "$output_dir" "par_extension_opt=replace; par_extension=png; par_suffix='(alpha 15 pct)'")
    std_output=$(_cmd_magick_convert "$input_file" \
        -alpha off \
        -bordercolor "$first_pixel_color" \
        -border 1 \( +clone \
        -fuzz 15% \
        -fill none \
        -floodfill +0+0 "$first_pixel_color" \
        -alpha extract \
        -geometry 200% \
        -blur 0x0.5 \
        -morphology erode square:1 \
        -geometry 50% \) \
        -compose CopyOpacity \
        -composite \
        -shave 1 \
        "$output_file" 2>&1)
    _check_output "$?" "$std_output" "$input_file" "$output_file" || return 1
}

_main "$@"
