#!/usr/bin/env bash

# Import the script 'common-functions.sh'
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(echo "$SCRIPT_DIR" | grep --only-matching "^.*scripts[^/]*")
source "$ROOT_DIR/common-functions.sh"

# Initial checks
_check_dependencies "iconv(libc-bin)"
_display_wait_box
INPUT_FILES=$(_get_files "$*" "type=all")

_main_task() {
    local INPUT_FILE=$1
    local OUTPUT_DIR=$2
    local OUTPUT_FILE=""
    local STD_OUTPUT=""
    local DIR=""
    local FILENAME=""

    DIR=$(dirname "$INPUT_FILE")
    FILENAME=$(basename "$INPUT_FILE")

    # Run the main process
    OUTPUT_FILE=$(echo "$FILENAME" | iconv -f utf8 -t ascii//TRANSLIT)
    STD_OUTPUT=$(_move_file "when_conflict=skip" "$INPUT_FILE" "$DIR/$OUTPUT_FILE" 2>&1)
    _check_result "$?" "$STD_OUTPUT" "$INPUT_FILE" "" || return 1
}

_run_main_task_parallel "$INPUT_FILES" ""
_display_result_box ""
