#!/usr/bin/env bash

# Source the file 'scripts/common-functions'
# shellcheck disable=SC1090
source "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")" | sed 's|\(scripts\).*|\1/common-functions|')"

# Initial checks
INPUT_FILES=$(_get_files "$*" "" "1" "" "d") || exit 1
OUTPUT_DIR="$PWD"

for FILE in $INPUT_FILES; do
    # shellcheck disable=SC2001
    OUTPUT_FILE=$(echo "$FILE" | sed "s|[- \t][- \t]*|_|g;s|__*|_|g")
    STD_OUTPUT=$(_move_file "$FILE" "$OUTPUT_FILE" 2>&1)
    EXIT_CODE=$?

    _log_result_error "$FILE" "$STD_OUTPUT" "$OUTPUT_DIR" "$EXIT_CODE" ""
done

_display_result "$OUTPUT_DIR"
