#!/usr/bin/env bash

# Source the file 'scripts/common-functions'
# shellcheck disable=SC1090
source "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")" | sed 's|\(scripts\).*|\1/common-functions|')"

# Initial checks
INPUT_FILES=$(_get_files "$*" "" "1" "" "d") || exit 1
OUTPUT_DIR="$PWD"

_rename() {
    FILE_SRC="$1"
    FILE_DST="$2"
    TEMP_FILE=".$FILE_SRC.tmp"

    if [ "$FILE_SRC" = "$FILE_DST" ]; then
        return
    fi

    if [ -f "$FILE_DST" ] || [ -f "$TEMP_FILE" ]; then
        _log_error "$FILE_SRC" "It was not possible to rename the file." "$OUTPUT_DIR"
        return
    fi

    # Run the main process
    mv "$FILE_SRC" "$TEMP_FILE" && mv "$TEMP_FILE" "$FILE_DST"
}

for FILE in $INPUT_FILES; do
    # shellcheck disable=SC2001
    OUTPUT_FILE=$(echo "$FILE" | sed "s|[\_\s][\_\s]*|-|g;s|--*|-|g")
    _rename "$FILE" "$OUTPUT_FILE"
done

_display_result "$OUTPUT_DIR"
