#!/usr/bin/env bash

# Source the file 'scripts/common-functions'
# shellcheck disable=SC1090
source "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")" | sed 's|\(scripts\).*|\1/common-functions|')"

# Initial checks
INPUT_FILES=$(_get_files "$*" "" "1" "" "d") || exit 1
OUTPUT_DIR="$PWD"

NUM_SEQUENCE=1
for FILE in $INPUT_FILES; do
    OUTPUT_FILE="$(printf "%01d" $NUM_SEQUENCE)$(_get_filename_extension "$FILE")"
    STD_OUTPUT=$(_transfer_file "M" "$FILE" "$OUTPUT_FILE" 2>&1)
    EXIT_CODE=$?
    _log_result_error "$FILE" "$STD_OUTPUT" "$OUTPUT_DIR" "$EXIT_CODE" ""

    NUM_SEQUENCE=$((NUM_SEQUENCE + 1))
done

_display_result "$OUTPUT_DIR"
