#!/usr/bin/env bash

# Source the file 'scripts/common-functions'
# shellcheck disable=SC1090
source "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")" | sed 's|\(scripts\).*|\1/common-functions|')"

# Initial checks
INPUT_FILES=$(_get_files "$*" "" "1" "" "R") || exit 1
OUTPUT_DIR="$PWD"

for FILE in $INPUT_FILES; do
    # Add the './' prefix
    if ! [[ "$FILE" == "/"* ]] && ! [[ "$FILE" == "./"* ]]; then
        FILE="./$FILE"
    fi

    FILE_DIR="${FILE%/*}"
    FILE_NAME="${FILE##*/}"
    FILE_NAME_NEW="${FILE_NAME,,}"
    OUTPUT_FILE="$FILE_DIR/$FILE_NAME_NEW"

    _transfer_file "m" "$FILE" "$OUTPUT_FILE"
    EXIT_CODE=$?
    _log_error_result "$FILE" "" "$OUTPUT_DIR" "$EXIT_CODE" ""
done

_display_result_tasks "$OUTPUT_DIR"
