#!/usr/bin/env bash

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
# shellcheck source=/dev/null
source "${SCRIPT_DIR%/*}/common-functions"

# Initial checks
INPUT_FILES=$(_get_files "$*" "" "1" "" "R") || exit 1
OUTPUT_DIR="$PWD"

for FILE in $INPUT_FILES; do
    # Add the './' prefix
    if ! [[ "$FILE" == "/"* ]] && ! [[ "$FILE" == "./"* ]]; then
        FILE="./$FILE"
    fi

    FILE_DIR="${FILE%/*}"
    FILE_NAME="${FILE##*/}"
    FILE_NAME_NEW="${FILE_NAME,,}"
    OUTPUT_FILE="$FILE_DIR/$FILE_NAME_NEW"

    STD_OUTPUT=$(_transfer_file "m" "$FILE" "$OUTPUT_FILE" 2>&1)
    EXIT_CODE=$?
    _log_error_result "$FILE" "$STD_OUTPUT" "$OUTPUT_DIR" "$EXIT_CODE" ""
done

_display_result_tasks "$OUTPUT_DIR"
