#!/usr/bin/env bash

# Source the file 'scripts/common-functions'
# shellcheck disable=SC1090
source "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")" | sed 's|\(scripts\).*|\1/common-functions|')"

# Initial checks
INPUT_FILES=$(_get_files "$*" "" "1" "" "d") || exit 1
OUTPUT_DIR="$PWD"

_main_task() {
    local FILE="$1"
    local OUTPUT_DIR="$2"
    local OUTPUT_FILE=""
    local EXIT_CODE=0

    OUTPUT_FILE="${FILE^^}"
    _transfer_file "m" "$FILE" "$OUTPUT_FILE"
    EXIT_CODE=$?
    _log_error_result "$FILE" "" "$OUTPUT_DIR" "$EXIT_CODE" ""
}

_run_parallel_tasks "$INPUT_FILES"
_display_result_tasks "$OUTPUT_DIR"
