#!/usr/bin/env bash

# Source the file 'scripts/common-functions'
# shellcheck disable=SC1090
source "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")" | sed 's|\(scripts\).*|\1/common-functions|')"

# Initial checks
INPUT_FILES=$(_get_files "$*" "" "1" "" "d") || exit 1
OUTPUT_DIR="$PWD"

for FILE in $INPUT_FILES; do
    OUTPUT_FILE="${FILE^^}"
    STD_OUTPUT=$(_move_file "$FILE" "$OUTPUT_FILE" 2>&1)
    EXIT_CODE=$?

    _log_result_error "$FILE" "$STD_OUTPUT" "$OUTPUT_DIR" "$EXIT_CODE" ""

    if [ -d "$OUTPUT_FILE" ]; then
        # Get the depth of the directory
        DEPTH=$(find -L "$OUTPUT_FILE" -type d -printf "%d\n" | sort -V -n -r | head -1)

        # Iterate over depths
        for ((i = 1; i <= DEPTH + 1; i++)); do
            INPUT_FILES_DEPTH=$(find -L "$OUTPUT_FILE" -mindepth "$i" -maxdepth "$i")
            # Rename files for current depth
            for FILE_DEPTH in $INPUT_FILES_DEPTH; do
                STD_OUTPUT=$(_move_file "$FILE_DEPTH" "${FILE_DEPTH^^}" 2>&1)
                EXIT_CODE=$?

                _log_result_error "$FILE_DEPTH" "$STD_OUTPUT" "$OUTPUT_DIR" "$EXIT_CODE" ""
            done
        done
    fi
done

_display_result "$OUTPUT_DIR"
