#!/usr/bin/env bash

# Source the file 'scripts/common-functions'
# shellcheck disable=SC1090
source "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")" | sed 's|\(scripts\).*|\1/common-functions|')"

# Initial checks
INPUT_FILES=$(_get_files "$*" "" "1" "" "d") || exit 1
OUTPUT_DIR="$PWD"

for FILE in $INPUT_FILES; do
    OUTPUT_FILE="${FILE^^}"
    _move_file "$FILE" "$OUTPUT_FILE"
done

_display_result "$OUTPUT_DIR"
