#!/usr/bin/env bash

# Import the script 'common-functions.sh'
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(echo "$SCRIPT_DIR" | grep --only-matching "^.*scripts[^/]*")
source "$ROOT_DIR/common-functions.sh"

# Initial checks
_check_dependencies "meld"
INPUT_FILES=$(_get_files "$*" "type=all; min_files=2; max_files=3")

# Run the main process
# shellcheck disable=SC2086
meld $INPUT_FILES &
