#!/usr/bin/env bash

# Source the script 'common-functions.sh'.
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/common-functions.sh"

_main() {
    local input_files=""
    local std_output=""

    # Execute initial checks.
    _check_dependencies ""
    _display_wait_box
    input_files=$(_get_files "type:all, min_files:2, max_files:2")

    # Run the main process.
    # shellcheck disable=SC2086
    std_output=$(diff --brief --recursive -- $input_files)
    std_output=$(_text_remove_pwd "$std_output")
    std_output=$(_text_sort "$std_output")

    _display_text_box "$std_output"
}

_main "$@"
