#!/usr/bin/env bash
# install_keyboard_shortcut=<Control><Alt>U

# Source the script '.common-functions.sh'.
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/.common-functions.sh"

_main() {
    local input_files=""
    local std_output=""

    # Execute initial checks.
    _check_dependencies "jdupes"
    _display_wait_box
    input_files=$(_get_files "par_type=all")

    # Run the main process.
    # shellcheck disable=SC2086
    std_output=$(LC_ALL=C jdupes --recurse --hard-links -X nostr:.git/ -- $input_files)
    std_output=$(grep -v -x -F "No duplicates found." <<<"$std_output")

    # Insert group numbers.
    std_output=$(awk 'NF == 0 { g++; next } { print g+1 "\r" $0 }' <<<"$std_output")

    std_output=$(_text_remove_pwd "$std_output")

    _display_list_box "$std_output" "par_item_name=$(_i18n 'files'); par_columns='--column:$(_i18n 'Group'),--column:$(_i18n 'File')'; par_action=open_location; par_check_type=checkbox"
}

_main "$@"
