#!/usr/bin/env bash

# Source the script 'common-functions.sh'.
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/common-functions.sh"

_main() {
    local input_files=""
    local std_output=""

    # Execute initial checks.
    _check_dependencies ""
    _display_wait_box "2"
    input_files=$(_get_files "par_type=all; par_get_pwd=true")

    # Run the main process.
    # shellcheck disable=SC2086
    std_output=$(find $input_files \
        ! -path "$IGNORE_FIND_PATH" \
        \( \
        -type d -iname "__pycache__" -o \
        -type d -iname ".caltrash" -o \
        -type d -iname ".fseventsd" -o \
        -type d -iname ".gradle" -o \
        -type d -iname ".idea" -o \
        -type d -iname ".mypy_cache" -o \
        -type d -iname ".pytest_cache" -o \
        -type d -iname ".Spotlight-V100" -o \
        -type d -iname ".TemporaryItems" -o \
        -type d -iname ".trash" -o \
        -type d -iname "*.tmp" -o \
        -type d -iname "latex.out" -o \
        -type f -iname "._*" -o \
        -type f -iname ".*.swo" -o \
        -type f -iname ".*.swp" -o \
        -type f -iname ".DS_Store*" -o \
        -type f -iname ".fseventsd-uuid" -o \
        -type f -iname ".goutputstream-*" -o \
        -type f -iname ".VolumeIcon.icns" -o \
        -type f -iname "*-jvsc-*.ipynb" -o \
        -type f -iname "*.~*" -o \
        -type f -iname "*.autosave.xopp" -o \
        -type f -iname "*.class" -o \
        -type f -iname "*.crdownload" -o \
        -type f -iname "*.fuse_hidden*" -o \
        -type f -iname "*.lock" -o \
        -type f -iname "*.log.lck" -o \
        -type f -iname "*.log" -o \
        -type f -iname "*.old" -o \
        -type f -iname "*.orig" -o \
        -type f -iname "*.part" -o \
        -type f -iname "*.pid" -o \
        -type f -iname "*.pyc" -o \
        -type f -iname "*.pyo" -o \
        -type f -iname "*.tmp" -o \
        -type f -iname "~lock.*" -o \
        -type f -iname "condaenv.*.requirements.txt" -o \
        -type f -iname "desktop.ini" -o \
        -type f -iname "ehthumbs.db" -o \
        -type f -iname "npm-debug.log*" -o \
        -type f -iname "Thumbs.db" -o \
        -type f -iname "yarn-*.log*" \
        \) -printf "%p\n" 2>/dev/null)

    std_output=$(_text_remove_pwd "$std_output")

    _display_list_box "$std_output" "par_columns='--column:File'; par_item_name='junk files'; par_action=delete_item; par_checkbox=true; par_checkbox_value=true"
}

_main "$@"
