#!/usr/bin/env bash
# shellcheck disable=SC2001
# install_keyboard_shortcut=<Control><Alt>U

# Source the script '_common-functions.sh'.
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/_common-functions.sh"

_main() {
    local input_files=""
    local std_output=""
    local temp_file=""

    # Execute initial checks.
    _check_dependencies "rdfind"
    _display_wait_box "2"
    input_files=$(_get_files "par_type=all")

    # Work on a temporary file.
    temp_file=$(_make_temp_file)

    # Run the main process.
    # shellcheck disable=SC2086
    # NOTE: The 'rdfind' does not support '--' in the command line.
    rdfind -dryrun true -removeidentinode false -outputname "$temp_file" $input_files &>/dev/null

    # FORMAT THE OUTPUT:
    # Extract lines containing 'DUPTYPE'.
    std_output=$(grep "DUPTYPE" <"$temp_file")
    rm -f -- "$temp_file"

    # Retain only the fields 2 (id) and 8 (name).
    std_output=$(cut -d " " -f 2,8- <<<"$std_output")

    # Remove the '-' before the IDs.
    std_output=$(sed "s|^-||" <<<"$std_output")

    # Insert '$FIELD_SEPARATOR' after the first field.
    std_output=$(sed "s|^\([0-9]*\)\ |\1$FIELD_SEPARATOR|" <<<"$std_output")

    # Exclude files located in '.git' directories.
    std_output=$(grep -v "/\.git/" <<<"$std_output")

    # Replace double slashes '//' with a single slash '/'.
    std_output=$(sed "s|//|/|" <<<"$std_output")

    std_output=$(_text_remove_pwd "$std_output")
    std_output=$(_text_sort "$std_output")

    _display_list_box "$std_output" "par_columns='--column:Group ID,--column:File'; par_item_name='duplicate files'; par_action=open_location; par_checkbox=true"
}

_main "$@"
