#!/usr/bin/env bash
# install_keyboard_shortcut=<Control><Shift>H

# Source the script 'common-functions.sh'.
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/common-functions.sh"

_main() {
    local input_files=""
    local std_output=""

    # Execute initial checks.
    _dependencies_check_commands ""
    _display_wait_box "2"
    input_files=$(_get_files "par_type=all")

    # Run the main process.
    # shellcheck disable=SC2086
    std_output=$(find -L $input_files ! -path "$IGNORE_FIND_PATH" -regextype posix-extended -regex ".*/\.[^/]*" -printf "%p\n" 2>/dev/null)
    std_output=$(_text_remove_pwd "$std_output")

    _display_list_box "$std_output" "par_columns='--column:Item'; par_item_name='hidden items'; par_action=open_location; par_checkbox=true"
}

_main "$@"
