#!/usr/bin/env bash
# install_keyboard_shortcut=<Control><Shift>E

# Source the script 'common-functions.sh'.
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/common-functions.sh"

_main() {
    local input_files=""
    local std_output=""

    # Execute initial checks.
    _check_dependencies ""
    _display_wait_box "2"
    input_files=$(_get_files "par_type=directory; par_get_pwd=true")

    # Run the main process.
    # shellcheck disable=SC2086
    std_output=$(find $input_files -type d -empty ! -path "$IGNORE_FIND_PATH" -printf "%p\n" 2>/dev/null)
    std_output=$(_text_remove_pwd "$std_output")

    _display_list_box "$std_output" "--column=Directory" "empty directories"
}

_main "$@"
