#!/usr/bin/env bash

# shellcheck disable=SC2001

# Import the script 'common-functions.sh'
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/common-functions.sh"

# Initial checks
_check_dependencies "rdfind"
_display_wait_box
input_files=$(_get_files "$*" "type=all")

# Work on a temporary file
temp_file=$(mktemp --tmpdir="$TEMP_DIR_TASK")

# Run the main process
# shellcheck disable=SC2086
rdfind -dryrun true -outputname "$temp_file" $input_files &>/dev/null
std_output=$(grep -v "^#" <"$temp_file")
std_output=$(grep -v ".*\.git/.*" <<<"$std_output")
std_output=$(cut -d ' ' -f 1,8- <<<"$std_output")
std_output=$(sed "s|\([^ ]*\)[ \t]*\(.*\)|\1 \"\2\"|" <<<"$std_output")
std_output=$(sed "s|DUPTYPE_FIRST_OCCURRENCE|\nDUPTYPE_FIRST_OCCURRENCE|" <<<"$std_output")
std_output=$(cut -d ' ' -f 2- <<<"$std_output")

# Remove the temporary files
rm -rf "$temp_file"

_display_text_box "$std_output"
