#!/usr/bin/env bash

# Source the script 'common-functions.sh'
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/common-functions.sh"

_main() {
    local input_files=""
    local std_output=""

    # Execute initial checks.
    _check_dependencies ""
    _display_wait_box
    input_files=$(_get_files "type:all, recursive:true, min_files:0, get_pwd_if_no_selection:true, extension:/\.[^/]*")

    # Run the main process.
    std_output=$(tr "$FILENAME_SEPARATOR" "\n" <<<"$input_files")
    std_output=$(_text_remove_pwd "$std_output")
    # shellcheck disable=SC2001
    std_output=$(sed "s|^\(..*\)$|'\1'|" <<<"$std_output")

    _display_text_box "$std_output"
}

_main "$@"
