#!/usr/bin/env bash

# shellcheck disable=SC2001

# Import the script 'common-functions.sh'
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/common-functions.sh"

# Initial checks
_check_dependencies ""
_display_wait_box
input_files=$(_get_files "$*" "type=file; recursive=true")

# Run the main process
# shellcheck disable=SC2086
std_output=$(file --separator "//" --no-pad $input_files 2>/dev/null)
std_output=$(sed "s|\(.*\)// *\(.*\)|\2: \"\1\"|" <<<"$std_output")
std_output=$(sort --version-sort <<<"$std_output")

_display_text_box "$std_output"
