#!/usr/bin/env bash

# Source the script 'common-functions.sh'.
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/common-functions.sh"

_main() {
    local input_files=""
    local std_output=""

    # Execute initial checks.
    _check_dependencies ""
    _display_wait_box "2"
    input_files=$(_get_files "par_type=all; par_recursive=true; par_get_pwd=true; par_min_files=0; par_select_regex='.*/\.[^/]*'")

    # Run the main process.
    std_output=$(_convert_filenames_to_text "$input_files")
    std_output=$(_text_remove_pwd "$std_output")
    # shellcheck disable=SC2001
    std_output=$(sed "s|^\(..*\)$|\1|" <<<"$std_output")

    _display_list_box "$std_output" "--column=Item"
}

_main "$@"
