#!/usr/bin/env bash

# Import the script 'common-functions.sh'
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/common-functions.sh"

_main() {
    local input_files=""
    local std_output=""

    # Initial checks
    _check_dependencies ""
    _display_wait_box
    input_files=$(_get_files "$*" "type=directory; get_pwd_if_no_selection=true")

    # Run the main process
    # shellcheck disable=SC2086
    std_output=$(du -h -- $input_files 2>/dev/null)
    # shellcheck disable=SC2001
    std_output=$(sed "s|$PWD/|./|g" <<<"$std_output") # Remove dir $PWD of the filename
    std_output=$(sort -h -r <<<"$std_output")
    std_output=$(head -n 10 <<<"$std_output")
    std_output=$(sed -r "s|\t(.*)|\t\"\1\"|" <<<"$std_output")

    _display_text_box "$std_output"
}

_main "$@"
