#!/usr/bin/env bash
# install_keyboard_shortcut=<Control><Alt>R

# Source the script '_common-functions.sh'.
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/_common-functions.sh"

_main() {
    local input_files=""
    local std_output=""

    # Execute initial checks.
    _check_dependencies ""
    _display_wait_box "2"
    input_files=$(_get_files "par_type=all")

    # Run the main process.
    # shellcheck disable=SC2086
    std_output=$(find -L $input_files -type f \
        ! -path "$IGNORE_FIND_PATH" ! -path '*/.*' \
        -printf "%TY-%Tm-%Td$FIELD_SEPARATOR%TH:%TM$FIELD_SEPARATOR%p\n" 2>/dev/null)
    std_output=$(_text_remove_pwd "$std_output")
    std_output=$(sort -k1,1r -k2,2r <<<"$std_output") # Sort the result.
    std_output=$(head -n 50 <<<"$std_output")

    _display_list_box "$std_output" "par_columns='--column:Date,--column:Time,--column:File'; par_item_name=files; par_resolve_links=false; par_action=open_location; par_checkbox=true"
}

_main "$@"
