#!/usr/bin/env bash

# Source the script '.common-functions.sh'.
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/.common-functions.sh"

_main() {
    local input_files=""
    local std_output=""

    # Execute initial checks.
    _check_dependencies ""
    _display_wait_box
    input_files=$(_get_files "par_type=directory; par_recursive=true")

    # Run the main process.
    std_output=$(printf "%s" "$input_files" | xargs \
        --no-run-if-empty --delimiter="$FIELD_SEPARATOR" \
        --replace="{}" du -sb {})

    std_output=$(tr "\t" "$FIELD_SEPARATOR" <<<"$std_output" |
        sort -n -r | head -n 15 |
        numfmt --to=iec --suffix=B --delimiter="$FIELD_SEPARATOR" --field=1)

    std_output=$(_text_remove_pwd "$std_output")

    _display_list_box "$std_output" "par_columns='--column:Size,--column:Directory'; par_item_name='largest directories'; par_action=open_location; par_checkbox=true"
}

_main "$@"
