#!/usr/bin/env bash

# Source the script '.common-functions.sh'.
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/.common-functions.sh"

_main() {
    local input_files=""
    local output_dir=""

    # Execute initial checks.
    _check_dependencies ""
    _display_wait_box "2"
    input_files=$(_get_files "par_type=all")

    if ! _display_question_box "This action will reset the permissions recursively.\n\nWould you like to continue?"; then
        _exit_script
    fi

    # Run the main process.
    new_pemission=$(printf "%04o" "$((0666 - $(umask)))")
    # shellcheck disable=SC2086
    std_output=$(find $input_files \
        ! -path "$IGNORE_FIND_PATH" \
        -type f -exec chmod "$new_pemission" -- {} + 2>&1)
    _check_output "$?" "$std_output" "" ""

    new_pemission=$(printf "%04o" "$((0777 - $(umask)))")
    # shellcheck disable=SC2086
    std_output=$(find $input_files \
        ! -path "$IGNORE_FIND_PATH" \
        -type d -exec chmod "$new_pemission" -- {} + 2>&1)
    _check_output "$?" "$std_output" "" ""

    _display_result_box ""
}

_main "$@"
