#!/usr/bin/env bash

# Source the script '.common-functions.sh'.
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/.common-functions.sh"

_main() {
    local input_files=""
    local output_dir=""

    # Execute initial checks.
    _check_dependencies "exiftool"
    _display_wait_box
    input_files=$(_get_files "par_type=file; par_recursive=true")

    # Execute the function '_main_task' for each file in parallel.
    _run_task_parallel "$input_files" "$output_dir"

    local std_output=""
    std_output=$(_storage_text_read_all)

    # Translate some strings from the '$std_output'.
    # shellcheck disable=SC2001
    std_output=$(sed "s|__MSG_File__|$(_i18n 'File')|g" <<<"$std_output")

    _display_text_box "$std_output"
}

_main_task() {
    local input_file=$1
    local output_dir=$2
    local std_output=""
    local status="🟢"

    # Run the main process.
    std_output=$(LC_ALL=C exiftool -- "$input_file" 2>/dev/null)

    # FORMAT THE OUTPUT:
    # Remove any extra spaces before colons ":".
    # shellcheck disable=SC2001
    std_output=$(sed "s| \+: |: |g" <<<"$std_output")
    # Remove irrelevant information.
    std_output=$(grep --ignore-case -v "^ExifTool Version Number: " <<<"$std_output")
    std_output=$(grep --ignore-case -v "^File name: " <<<"$std_output")
    std_output=$(grep --ignore-case -v "^Directory: " <<<"$std_output")

    if grep --quiet --ignore-case "^Error:" <<<"$std_output"; then
        status="🔴"
    fi

    # Prepend the filename.
    std_output="$status __MSG_File__: \"$(_text_remove_pwd "$input_file")\""$'\n'"$std_output"

    _storage_text_write_ln "$std_output"$'\n'
}

_main "$@"
