#!/usr/bin/env bash

# Source the script '.common-functions.sh'.
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/.common-functions.sh"

_main() {
    local input_files=""
    local output_dir=""

    # Execute initial checks.
    _check_dependencies "mediainfo"
    _display_wait_box
    input_files=$(_get_files "par_type=file; par_recursive=true; par_select_extension=mp3; par_skip_extension=bak")

    # Execute the function '_main_task' for each file in parallel.
    _run_task_parallel "$input_files" "$output_dir"

    local std_output=""
    std_output=$(_storage_text_read_all)
    std_output=$(_text_sort "$std_output")

    _display_list_box "$std_output" "par_item_name=$(_i18n 'files'); par_columns='--column:$(_i18n 'Mode'),--column:$(_i18n 'Bit rate'),--column:$(_i18n 'Sampling rate'),--column:$(_i18n 'Channels'),--column:$(_i18n 'File')'; par_action=open_location; par_checkbox=true"
}

_main_task() {
    local input_file=$1
    local output_dir=$2
    local std_output=""

    # Run the main process.
    std_output=$(mediainfo --Inform="Audio;BitRate_Mode:%BitRate_Mode%\nBitRate:%BitRate/String%\nSamplingRate:%SamplingRate/String%\nChannel(s):%Channel(s)/String%" -- "$input_file" 2>&1)
    _check_output "$?" "$std_output" "$input_file" "" || return 1

    local mode=""
    local bit_rate=""
    local sampling_rate=""
    local channels=""
    mode=$(grep -m1 "^BitRate_Mode:" <<<"$std_output" | cut -d ":" -f 2-)
    bit_rate=$(grep -m1 "^BitRate:" <<<"$std_output" | cut -d ":" -f 2-)
    sampling_rate=$(grep -m1 "^SamplingRate:" <<<"$std_output" | cut -d ":" -f 2-)
    channels=$(grep -m1 "^Channel" <<<"$std_output" | cut -d ":" -f 2-)

    # Check if the values are not empty.
    if [[ -z "$mode" ]]; then
        mode=" "
    fi
    if [[ -z "$bit_rate" ]]; then
        bit_rate=" "
    fi
    if [[ -z "$sampling_rate" ]]; then
        sampling_rate=" "
    fi
    if [[ -z "$channels" ]]; then
        channels=" "
    fi

    _storage_text_write_ln "$mode$FIELD_SEPARATOR$bit_rate$FIELD_SEPARATOR$sampling_rate$FIELD_SEPARATOR$channels$FIELD_SEPARATOR$(_text_remove_pwd "$input_file")"
}

_main "$@"
