#!/usr/bin/env bash

# Source the script '.common-functions.sh'.
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/.common-functions.sh"

_main() {
    local input_files=""
    local output_dir=""

    # Execute initial checks.
    _check_dependencies "mediainfo"
    _display_wait_box
    input_files=$(_get_files "par_type=file; par_recursive=true; par_select_extension=mp3; par_skip_extension=bak")

    # Execute the function '_main_task' for each file in parallel.
    _run_task_parallel "$input_files" "$output_dir"
    _display_result_box ""
}

_main_task() {
    local input_file=$1
    local output_dir=$2
    local std_output=""

    # Run the main process.
    std_output=$(LC_ALL=C mediainfo --Inform="General;Title:%Title%\nPerformer:%Performer%" -- "$input_file" 2>&1)
    _check_output "$?" "$std_output" "$input_file" "" || return 1

    local tag_artist=""
    local tag_title=""
    tag_artist=$(grep -m1 "^Performer:" <<<"$std_output" | cut -d ":" -f 2-)
    tag_title=$(grep -m1 "^Title:" <<<"$std_output" | cut -d ":" -f 2-)

    # Rename the file.
    local dir_file=""
    dir_file=$(_get_filename_dir "$input_file")
    _move_file "rename" "$input_file" "$dir_file/$tag_artist - $tag_title.mp3" || return 1
}

_main "$@"
