#!/usr/bin/env bash

# Import the script 'common-functions.sh'
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/common-functions.sh"

# Initial checks
_check_dependencies "findimagedupes eog"
_display_wait_box
input_files=$(_get_files "$*" "type=file_recursive; mime=image")

# Run the main process
# shellcheck disable=SC2086
findimagedupes --recurse --threshold=55% --program=/usr/bin/eog -- $input_files 2>/dev/null
_display_result_box ""
