#!/usr/bin/env bash

# Import the script 'common-functions.sh'
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
source "${SCRIPT_DIR/%scripts\/*/scripts}/common-functions.sh"

# Initial checks
_check_dependencies "findimagedupes eog"
_display_wait_box
INPUT_FILES=$(_get_files "$*" "type=file_recursive; mime=image")

# Run the main process
# shellcheck disable=SC2086
findimagedupes --recurse --threshold=65% --program=/usr/bin/eog -- $INPUT_FILES 2>/dev/null
_display_result_box ""
