#!/usr/bin/env bash

# Source the script '.common-functions.sh'.
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/.common-functions.sh"

_main() {
    local input_files=""
    local output_dir=""

    # Execute initial checks.
    _check_dependencies ""
    _display_wait_box "2"
    input_files=$(_get_files "par_type=all")
    output_dir=$(_get_desktop_dir)

    # Execute the function '_main_task' for each file in parallel.
    _run_task_parallel "$input_files" "$output_dir"
    _display_result_box "$output_dir"
}

_main_task() {
    local input_file=$1
    local output_dir=$2
    local output_file=""
    local std_output=""

    # Run the main process.
    output_file=$(_get_output_filename "$input_file" "$output_dir" "par_extension_opt=preserve")
    std_output=$(ln -s -- "$input_file" "$output_file" 2>&1)
    _check_output "$?" "$std_output" "$input_file" "$output_file" || return 1
}

_get_desktop_dir() {
    local desktop_dir=""

    # Get the path of the Desktop directory.
    desktop_dir=$(xdg-user-dir DESKTOP 2>/dev/null)
    if [[ ! -d "$desktop_dir" ]]; then
        desktop_dir="$HOME/Desktop"
    fi

    if [[ ! -d "$desktop_dir" ]]; then
        _display_error_box "Could not find the Desktop directory."
        _exit_script
    fi

    printf "%s" "$desktop_dir"
}

_main "$@"
