#!/usr/bin/env bash

# Source the script '_common-functions.sh'.
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/_common-functions.sh"

_main() {
    local input_files=""
    local std_output=""

    # Execute initial checks.
    _dependencies_check_commands ""
    _display_wait_box "2"
    input_files=$(_get_files "par_type=all")

    # Run the main process.
    # shellcheck disable=SC2086
    std_output=$(find -L $input_files -type f ! -path "$IGNORE_FIND_PATH" -links +1 -printf "%i$FIELD_SEPARATOR%p\n" 2>/dev/null)
    std_output=$(_text_remove_pwd "$std_output")
    std_output=$(_text_sort "$std_output")

    _display_list_box "$std_output" "par_columns='--column:Inode,--column:File'; par_item_name='hard links'; par_action=open_location; par_checkbox=true"
}

_main "$@"
