#!/usr/bin/env bash
# install_keyboard_shortcut=<Control><Shift>V

# Source the script 'common-functions.sh'.
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/common-functions.sh"

_main() {
    local output_dir=""

    # Execute initial checks.
    _check_dependencies_clipboard ""

    _display_wait_box "2"
    output_dir=$(_get_output_dir "par_use_same_dir=true")

    # Execute the function '_main_task' for each file in parallel.
    _run_task_parallel "$(_get_uris)" "$output_dir"
    _display_result_box "$output_dir"
}

_main_task() {
    local input_file=$1
    local output_dir=$2
    local std_output=""

    if [[ ! -e "$input_file" ]]; then
        return 1
    fi

    _directory_push "$output_dir" 2>/dev/null || return 1

    # Run the main process.
    output_file=$(_get_output_filename "$input_file" "$output_dir" "par_extension_opt=preserve")
    std_output=$(ln -s -- "$input_file" "$output_file" 2>&1)
    _check_output "$?" "$std_output" "$input_file" "$output_file" || return 1
}

_get_uris() {
    local uris=""

    uris=$(_get_clipboard_data)
    uris=$(grep --only-matching --perl-regexp "^(file://|('\")?/)(.*)" <<<"$uris")
    uris=$(sed "s|^['\"]||g; s|['\"]$||g" <<<"$uris")
    uris=$(sort --unique <<<"$uris")

    if [[ -z "$uris" ]]; then
        _display_error_box "There are no valid paths in the clipboard!"
        _exit_script
    fi

    uris=$(_convert_text_to_delimited_string "$uris")
    uris=$(_text_uri_decode "$uris")

    printf "%s" "$uris"
}

_main "$@"
