#!/usr/bin/env bash

# Import the script 'common-functions.sh'
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
source "${SCRIPT_DIR/%scripts\/*/scripts}/common-functions.sh"

# Initial checks
_check_dependencies "ffmpeg"
_display_wait_box
INPUT_FILES=$(_get_files "$*" "type=file; mime=audio,video,stream; min_files=2; max_files=2")
OUTPUT_DIR=$(_get_output_dir)

_task() {
    local INPUT_FILES=$1
    local OUTPUT_DIR=$2
    local OUTPUT_FILE=""
    local STD_OUTPUT=""
    local INPUT_FILE_1=""
    local INPUT_FILE_2=""

    INPUT_FILE_1=$(echo "$INPUT_FILES" | sed -n 1p)
    INPUT_FILE_2=$(echo "$INPUT_FILES" | sed -n 2p)

    # Run the main process
    OUTPUT_FILE="$OUTPUT_DIR/mixed-audio.wav"
    STD_OUTPUT=$(ffmpeg -threads 4 -y -i "$INPUT_FILE_1" -i "$INPUT_FILE_2" -filter_complex "amix=inputs=2:duration=longest" "$OUTPUT_FILE" 2>&1)
    _check_result "$?" "$STD_OUTPUT" "" "$OUTPUT_FILE" || return 1
}

_task "$INPUT_FILES" "$OUTPUT_DIR"
_display_result_box "$OUTPUT_DIR"
