#!/usr/bin/env bash

# Import the script 'common-functions.sh'
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/common-functions.sh"

_main() {
    local input_files=""
    local output_dir=""

    # Initial checks
    _check_dependencies "photorec(testdisk)"
    _display_wait_box
    input_files=$(_get_files "$*" "type=file")
    output_dir=$PWD

    _run_main_task_parallel "$input_files" "$output_dir"
    _display_result_box "$output_dir"
}

_main_task() {
    local input_file=$1
    local output_dir=$2
    local std_output=""

    # Run the main process
    output_dir="$(_get_filename_without_extension "$input_file")-output"
    std_output=$(photorec /d "$output_dir" /cmd "$input_file" partition_none,fileopt,everything,enable,search 2>&1)
    _check_result "$?" "$std_output" "$input_file" "" || return 1
}

_main "$@"
