#!/usr/bin/env bash

# Source the script 'common-functions.sh'.
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/common-functions.sh"

_main() {
    local input_files=""
    local output_dir=""

    # Execute initial checks.
    _check_dependencies "
        command=photorec; pkg_manager=apt; package=testdisk |
        command=photorec; pkg_manager=dnf; package=testdisk |
        command=photorec; pkg_manager=pacman; package=testdisk |
        command=photorec; pkg_manager=zypper; package=photorec"
    _display_wait_box "2"
    input_files=$(_get_files "par_type=file")
    output_dir=$(_get_output_dir "par_use_same_dir=true")

    # Execute the function '_main_task' for each file in parallel.
    _run_task_parallel "$input_files" "$output_dir"
    _display_result_box "$output_dir"
}

_main_task() {
    local input_file=$1
    local output_dir=$2
    local std_output=""

    # Run the main process.
    output_dir="$(_strip_filename_extension "$input_file")-output"
    std_output=$(photorec /d "$output_dir" /cmd "$input_file" partition_none,fileopt,everything,enable,search 2>&1)
    _check_output "$?" "$std_output" "$input_file" "" || return 1
}

_main "$@"
