#!/usr/bin/env bash

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
# shellcheck source=/dev/null
source "${SCRIPT_DIR/%scripts\/*/scripts}/_common_functions"

# Initial checks
_check_dependencies meld || exit 1
INPUT_FILES=$(_get_files "$*" "f" "2" "3" "text;application") || exit 1

# Run the main process
# shellcheck disable=SC2086
meld $INPUT_FILES &
