#!/usr/bin/env bash

# Source the file 'scripts/common-functions'
# shellcheck disable=SC1090
source "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")" | sed 's|\(scripts\).*|\1/common-functions|')"

# Initial checks
_check_dependencies iconv
INPUT_FILES=$(_get_files "$*" "text;application" "1" "" "")
OUTPUT_DIR=$(_get_output_dir)

for FILE in $INPUT_FILES; do
    # Skip 'ascii' files
    if file -bi "$FILE" | grep -q -- "ascii"; then
        continue
    fi

    # Run the main process
    OUTPUT_FILE="$OUTPUT_DIR/$FILE"
    STD_OUTPUT="$(iconv -f "$(file -bi "$FILE" | cut -d '=' -f 2)" "$FILE" -t ascii//TRANSLIT -o "$OUTPUT_FILE")"
    EXIT_CODE=$?

    _log_result_error "$FILE" "$STD_OUTPUT" "$OUTPUT_DIR" "$EXIT_CODE" "$OUTPUT_FILE"
done

_display_result "$OUTPUT_DIR"
