#!/usr/bin/env bash

# Source the file 'scripts/common-functions'
# shellcheck disable=SC1090
source "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")" | sed -z 's|\(scripts\).*|\1/common-functions|')"

# Initial checks
_check_dependency meld
INPUT_FILES=$(_check_files "$*" "" "2" "3" "d") || exit 1

# Run the main process
# shellcheck disable=SC2086
meld $INPUT_FILES
