#!/usr/bin/env bash

# Source the file 'scripts/common-functions'
# shellcheck disable=SC1090
source "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")" | sed 's|\(scripts\).*|\1/common-functions|')"

# Initial checks
_check_dependencies cmp iconv perl zenity || exit 1
INPUT_FILES=$(_get_files "$*" "text;application" "1" "" "r") || exit 1

OUTPUT_TEMP_FILE=$(mktemp)
STD_OUTPUT=""

for FILE in $INPUT_FILES; do
    # Skip 'binary' files
    if file -bi "$FILE" | grep -q "binary"; then
        continue
    fi

    RESULT_FILE=""

    # Run the checker 'non UTF-8 encoding'
    iconv -f "$(file -bi "$FILE" | cut -d '=' -f 2)" "$FILE" -t utf-8 -o "$OUTPUT_TEMP_FILE"
    if ! cmp --silent "$FILE" "$OUTPUT_TEMP_FILE"; then
        RESULT_FILE+="[non UTF-8 encoding]"
    fi

    # Run the checker 'non LF line break'
    perl -pe 's/\r\n|\n|\r/\n/g' "$FILE" >"$OUTPUT_TEMP_FILE"
    if ! cmp --silent "$FILE" "$OUTPUT_TEMP_FILE"; then
        RESULT_FILE+="[non LF line break]"
    fi

    # Run the checker 'has trailing spaces'
    sed "s|[ \t]*$||" "$FILE" >"$OUTPUT_TEMP_FILE"
    if ! cmp --silent "$FILE" "$OUTPUT_TEMP_FILE"; then
        RESULT_FILE+="[trailing spaces]"
    fi

    # Run the checker 'has many line breaks at the end'
    sed ':Loop;N;$!bLoop;s|\n*$||g' "$FILE" >"$OUTPUT_TEMP_FILE"
    if ! cmp --silent "$FILE" "$OUTPUT_TEMP_FILE"; then
        RESULT_FILE+="[many lines at the end]"
    fi

    # Run the checker 'missing line break at the end'
    if [[ -n "$(cat -e "$FILE" | tail -c 1)" ]]; then
        RESULT_FILE+="[missing line at the end]"
    fi

    # Run the checker 'has non ASCII characters'
    NON_ASCII_REGEX="[^ \w\t\n\r\-\,\;\:\!\?\.\'\"\(\)\[\]\{\}\@\*\/\\\&\#\%\`\^\+\<\=\>\|\~\$áàâãçéêíóôõú]"
    if grep -i -q -I -P "$NON_ASCII_REGEX" "$FILE"; then
        RESULT_FILE+="[non ASCII char]"
    fi

    # Add only the files that has problems
    if [[ -n "$RESULT_FILE" ]]; then
        STD_OUTPUT+="$RESULT_FILE"
        STD_OUTPUT+=": '$FILE'"
        STD_OUTPUT+=$'\n'
    fi
done

# Remove temporary file
rm -rf "$OUTPUT_TEMP_FILE"

STD_OUTPUT=$(echo "$STD_OUTPUT" | grep -v "^$")
STD_OUTPUT=$(echo "$STD_OUTPUT" | sort -V)

WIDTH_TEXT=$(echo "$STD_OUTPUT" | wc -L)
WIDTH_WINDOW=$((WIDTH_TEXT * 10))
echo "$STD_OUTPUT" | zenity --text-info --no-wrap --font="Liberation Mono" --height=300 --width="$WIDTH_WINDOW" --title "Text summary checker"
