#!/usr/bin/env bash

# Source the file 'scripts/common-functions'
# shellcheck disable=SC1090
source "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")" | sed 's|\(scripts\).*|\1/common-functions|')"

# Initial checks
_check_dependencies zenity || exit 1
INPUT_FILES=$(_get_files "$*" "text;application" "1" "" "r") || exit 1

OUTPUT_TEMP_FILE=$(mktemp)
STD_OUTPUT=""

for FILE in $INPUT_FILES; do
    # Skip 'binary' files
    if file -bi "$FILE" | grep -q "binary"; then
        continue
    fi

    RESULT_FILE=""
    FILE_ENCODING=$(file --mime-encoding "$FILE" | sed "s|\([^:]*\):[ \t]*\(.*\)|\2|")
    FILE_INFORMATION=$(file "$FILE" | sed "s|\([^:]*\):[ \t]*\(.*\)|\2|")

    # Run the checker 'non UTF-8 encoding'
    if [[ "${FILE_ENCODING,,}" != *"us-ascii"* ]] && [[ "${FILE_ENCODING,,}" != *"utf-8"* ]]; then
        RESULT_FILE+="[non UTF-8 encoding]"
    fi

    # Run the checker 'non LF line break'
    if [[ "$FILE_INFORMATION" == *"with CR"* ]]; then
        RESULT_FILE+="[non LF line break]"
    fi

    # Run the checker 'trailing spaces' (for Unix and Windows files)
    if grep -P -q "[ \t]\r?$" "$FILE"; then
        RESULT_FILE+="[trailing spaces]"
    fi

    # Run the checker 'trailing spaces' (for Mac files)
    if [[ "$FILE_INFORMATION" == *"with CR line"* ]] || [[ "$FILE_INFORMATION" == *"with CR, LF line"* ]]; then
        if cat -A "$FILE" | grep -q " ^M"; then
            RESULT_FILE+="[trailing spaces]"
        fi
    fi

    # Run the checker 'missing line break at the end'
    if ! tail -c 1 "$FILE" | hexdump -e '16/1 "%02x" "\n"' | grep -q "0d\|0a"; then
        RESULT_FILE+="[missing line at the end]"
    else
        if tail -c 3 "$FILE" | hexdump -e '16/1 "%02x" "\n"' | grep -q "..0d0d\|..0a0a\|0a0d0a"; then
            # Run the checker 'has many line breaks at the end'
            RESULT_FILE+="[many lines at the end]"
        fi
    fi

    # Add only the files that has problems
    if [[ -n "$RESULT_FILE" ]]; then
        STD_OUTPUT+="$RESULT_FILE"
        STD_OUTPUT+=": '$FILE'"
        STD_OUTPUT+=$'\n'
    fi
done

# Remove temporary file
rm -rf "$OUTPUT_TEMP_FILE"

STD_OUTPUT=$(echo "$STD_OUTPUT" | grep -v "^$")
STD_OUTPUT=$(echo "$STD_OUTPUT" | sort -V)

WIDTH_TEXT=$(echo "$STD_OUTPUT" | wc -L)
WIDTH_WINDOW=$((WIDTH_TEXT * 10))
echo "$STD_OUTPUT" | zenity --text-info --no-wrap --font="Liberation Mono" --height=300 --width="$WIDTH_WINDOW" --title "Text: summary checker"
