#!/usr/bin/env bash

# shellcheck disable=SC2001

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
# shellcheck source=/dev/null
source "${SCRIPT_DIR%/*}/common-functions"

# Initial checks
_check_dependencies zenity || exit 1
INPUT_FILES=$(_get_files "$*" "text;application" "1" "" "r") || exit 1

# Run the main process
# shellcheck disable=SC2086
STD_OUTPUT=$(grep -i -r -I -P -o -n --exclude="*.pdf" --exclude-dir="*.git*" "[^ \w\t\n\r\-\,\;\:\!\?\.\'\"\(\)\[\]\{\}\@\*\/\\\&\#\%\`\^\+\<\=\>\|\~\$áàâãçéêíóôõú\“\”®§©ªº°¹²³]" $INPUT_FILES /dev/null)

_display_info_box "$STD_OUTPUT" "Find files: with bad chars"
