#!/usr/bin/env bash

# Source the script 'common-functions.sh'.
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(grep --only-matching "^.*scripts[^/]*" <<<"$SCRIPT_DIR")
source "$ROOT_DIR/common-functions.sh"

_main() {
    local input_files=""
    local output_dir=""

    # Execute initial checks.
    _check_dependencies "gpg(apt:gpg,pacman:gnupg,dnf:gnupg2)"
    _display_wait_box
    input_files=$(_get_files "type:file, extension:asc|gpg|pgp|sig")

    # Execute the function '_main_task' for each file in parallel.
    _run_task_parallel "$input_files" "$output_dir"

    std_output=$(cat -- "$TEMP_DIR_TASK/"* 2>/dev/null) # Compile all results into a single output.

    _display_text_box "$std_output"
}

_main_task() {
    local input_file=$1
    local output_dir=$2
    local temp_file=""
    local std_output=""

    # Run the main process.
    temp_file=$(mktemp --tmpdir="$TEMP_DIR_TASK")
    std_output=$(gpg --yes --verify -- "$input_file" 2>&1)

    echo "\"$(_text_remove_pwd "$input_file")\"" >"$temp_file"
    echo "$std_output" >>"$temp_file"
    echo >>"$temp_file"
}

_main "$@"
