#!/usr/bin/env bash

# Import the script 'common-functions.sh'
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(echo "$SCRIPT_DIR" | grep --only-matching "^.*scripts[^/]*")
source "$ROOT_DIR/common-functions.sh"

# Initial checks
_check_dependencies "expand(coreutils)"
_display_wait_box
INPUT_FILES=$(_get_files "$*" "type=file; mime=text,application; skip_encoding=binary; skip_extension=pdf")
OUTPUT_DIR=$(_get_output_dir)

_main_task() {
    local INPUT_FILE=$1
    local OUTPUT_DIR=$2
    local OUTPUT_FILE=""
    local STD_OUTPUT=""
    local TEMP_FILE=""

    # Work on a temporary file
    TEMP_FILE=$(mktemp --tmpdir="$TEMP_DIR_TASK")

    # Run the main process
    STD_OUTPUT=$(expand --tabs=4 "$INPUT_FILE" >"$TEMP_FILE")
    _check_result "$?" "$STD_OUTPUT" "$INPUT_FILE" "$OUTPUT_FILE" || return 1

    # Move the temporary file to the output
    OUTPUT_FILE=$(_get_output_file "$INPUT_FILE" "$OUTPUT_DIR" "")
    _move_temp_file_to_output "$INPUT_FILE" "$TEMP_FILE" "$OUTPUT_FILE" || return 1

    # Remove the temporary files on each iteration (if not removed before)
    rm -rf "$TEMP_FILE"
}

_run_main_task_parallel "$INPUT_FILES" "$OUTPUT_DIR"
_display_result_box "$OUTPUT_DIR"
