#!/usr/bin/env bash

# Source the file 'scripts/common-functions'
# shellcheck disable=SC1090
source "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")" | sed 's|\(scripts\).*|\1/common-functions|')"

# Initial checks
_check_dependencies convert || exit 1
INPUT_FILES=$(_get_files "$*" "image" "2" "" "") || exit 1
OUTPUT_DIR=$(_get_output_dir) || exit 1

# Run the main process
OUTPUT_FILE="$OUTPUT_DIR/image.gif"
# shellcheck disable=SC2086
STD_OUTPUT=$(convert -delay 100 -loop 0 $INPUT_FILES "$OUTPUT_FILE" 2>&1)
EXIT_CODE=$?

_log_error_result "$FILE" "$STD_OUTPUT" "$OUTPUT_DIR" "$EXIT_CODE" "$OUTPUT_FILE"
_display_result_tasks "$OUTPUT_DIR"
