#!/usr/bin/env bash

# Source the file 'scripts/common-functions'
# shellcheck disable=SC1090
source "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")" | sed 's|\(scripts\).*|\1/common-functions|')"

# Initial checks
_check_dependency convert
INPUT_FILES=$(_check_files "$*" "image" "2" "" "") || exit 1
OUTPUT_DIR=$(_get_output_dir)

# Run the main process
OUTPUT_FILE="$OUTPUT_DIR/image.gif"
# shellcheck disable=SC2086
STD_OUTPUT="$(convert -delay 100 -loop 0 $INPUT_FILES "$OUTPUT_FILE" 2>&1)"
EXIT_CODE=$?

# Check the return and log the error
if [ "$EXIT_CODE" -ne 0 ]; then
    _log_error "$INPUT_FILES" "$STD_OUTPUT" "$OUTPUT_DIR"
fi

_display_result "$OUTPUT_DIR"
